// noinspection JSNonASCIINames
export const SPOTIFY_TEST_ANSWERS: Record<string, string> = {
  'Muse – New Born': 'https://open.spotify.com/track/2VrJMuLt2m9HbifGrKWHqk',
  'Shallows – Summer Sucks': 'https://open.spotify.com/track/3HKd06qhZs78WNZ22XAzPD',
  'Porcupine Tree – Sentimental': 'https://open.spotify.com/track/5pQNsm5hmOUVwgRtDGijyi',
  'Muse – Citizen Erased': 'https://open.spotify.com/track/177MZraDAxjRqqtZBz5Vhn',
  'Within Temptation – Ice Queen': 'https://open.spotify.com/track/140cSu65JC8smYw53nPP0q',
  'The Smiths – There Is a Light That Never Goes Out': 'https://open.spotify.com/track/1Oexe6ZYusAMbhUzzr87Iy',
  'Mauro Picotto – Komodo': 'https://open.spotify.com/track/61atdjQA36XqmQ4D4Fp2L6',
  'M83 – Wait': 'https://open.spotify.com/track/01Q3OyB05mLgH01fpdAMPP',
  'Beach House – Myth': 'https://open.spotify.com/track/2Zw3HNjaNV42LnQ2uY5JQs',
  'Linkin Park – In The End': 'https://open.spotify.com/track/6zyrb7dW1IR4Hrc8nXJsln',
  'Chvrches – Down Side Of Me': 'https://open.spotify.com/track/3E2qPa0kB1rl5JhXAo6QhX',
  'Twenty One Pilots – Car Radio': 'https://open.spotify.com/track/3zaCBaBsSii7XcHtPjlix5',
  'Meat Loaf – Bat out of Hell': 'https://open.spotify.com/track/3mCeeoBvTTpg8Xy2Wuvirw',
  'The Kelly Family – Fell in Love with an Alien': 'https://open.spotify.com/track/7ByhqIL2dqk4W0jPTkWc9A',
  'Nightwish – The Greatest Show on Earth': 'https://open.spotify.com/track/2TMBnZlhLEzMIpFBLlDdTh',
  'Coldplay – Viva la Vida': 'https://open.spotify.com/track/3Fcfwhm8oRrBvBZ8KGhtea',
  'Porcupine Tree – Arriving Somewhere But Not Here': 'https://open.spotify.com/track/6bz2YUk80Z3r4PNsbrWn2H',
  'CHVRCHES & Robert Smith – How Not To Drown': 'https://open.spotify.com/track/6Hqj8TOps7LeWwPCIyrder',
  'Led Zeppelin – Stairway to Heaven': 'https://open.spotify.com/track/7rltssh7c2cx6ztmftjiZ2',
  'Eros Ramazzotti – Un Emozione Per Sempre': 'https://open.spotify.com/track/1Hd8GLavCUUUx3GJdunJ4E',
  'Tame Impala – Let It Happen': 'https://open.spotify.com/track/2X485T9Z5Ly0xyaghN73ed',
  'Swedish House Mafia & The Weeknd – Moth to a Flame': 'https://open.spotify.com/track/7kfOEMJBJwdCYqyJeEnNhr',
  'The Haunted Youth – Broken': 'https://open.spotify.com/track/3EJ7h1f0Nvvnpt1mRNCcOz',
  'Billie Eilish – Everything I Wanted': 'https://open.spotify.com/track/3ZCTVFBt2Brf31RLEnCkWJ',
  'Alan Parsons Project – Old And Wise': 'https://open.spotify.com/track/5qdlMWYpCtJFsHey3rXYms',
  'Rondé – Headlights': 'https://open.spotify.com/track/4Ic1OpR1bm6jlDoXdFaXpg',
  'Dire Straits – Brothers In Arms': 'https://open.spotify.com/track/5t3ClpjiJUTCHKODTPrW8i',
  'Kaleo – Vor í Vaglaskógi': 'https://open.spotify.com/track/2OdpZeTpnbqPqBrclk2pib',
  'Rondé – Real Feelings': 'https://open.spotify.com/track/397Fqg8BPbeGfrYmKyIwK2',
  'Eminem – Stan': 'https://open.spotify.com/track/3UmaczJpikHgJFyBTAJVoz',
  'Foo Fighters – Everlong': 'https://open.spotify.com/track/5UWwZ5lm5PKu6eKsHAGxOk',
  'Emilie Autumn – Castle Down': 'doesnt exist',
  'Lights – Pretend': 'https://open.spotify.com/track/55o4enCNT1kXyYl641gDrc',
  'Beach House – Lazuli': 'https://open.spotify.com/track/2TIJiqr72Qe9tGd26fStIN',
  'Maitre Gims – J’me Tire': 'https://open.spotify.com/track/4w47YE9rjhmZUdtZjSCb82',
  'Kygo feat. DNCE – Dancing Feet': 'https://open.spotify.com/track/4RAR8g8fZNB106ezUurnE0',
  'Beach House – Beyond Love': 'https://open.spotify.com/track/0fbKFguQCxauLvVZ262f4c',
  'Girls in Hawaii – Misses': 'https://open.spotify.com/track/6GruFJTfZZqnb2osHcPE4c',
  'Billie Eilish – TV': 'https://open.spotify.com/track/3GYlZ7tbxLOxe6ewMNVTkw',
  'Delain – Silhouette of a Dancer': 'https://open.spotify.com/track/3k5zLvrnRqFVnTJg67zCwp',
  'Johnny Marr – New Town Velocity': 'https://open.spotify.com/track/65ZOtsTLMHkDywh4qDfASZ',
  'Placebo – Song to Say Goodbye': 'https://open.spotify.com/track/6Vkn98iI3sfATzdacZ307z',
  'Marc Korn feat. Chelsea Field – Touch the Sky': 'https://open.spotify.com/track/7aCtJ09CpGqH0UEDqcHemb',
  'Joci Pápai – Az Én Apám': 'https://open.spotify.com/track/7BxvOHOaRr6v7VDLKKdeYw',
  'Alan Walker – Faded': 'https://open.spotify.com/track/7gHs73wELdeycvS48JfIos',
  'Depeche Mode – Enjoy The Silence': 'https://open.spotify.com/track/6WK9dVrRABMkUXFLNlgWFh',
  'MGMT – Time To Pretend': 'https://open.spotify.com/track/4iG2gAwKXsOcijVaVXzRPW',
  'Avantasia – The Scarecrow': 'https://open.spotify.com/track/1bCTt8s6cMFww1SqtLuWpH',
  'Nightwish – Ghost Love Score': 'https://open.spotify.com/track/5dyQ8spGuggi5RBqhkUToy',
  'Tom Odell – Another Love': 'https://open.spotify.com/track/3JvKfv6T31zO0ini8iNItO',
  'The War on Drugs – Thinking Of a Place': 'https://open.spotify.com/track/4Sd5tbNP4q8wS64abqwfkN',
  'Meat Loaf – Blind as a Bat': 'https://open.spotify.com/track/66891lY85YJvkNrRepOEJa',
  'E-Type – Forever More': 'https://open.spotify.com/track/2bfxCJXbbTV4phk02ipGYm',
  'Skillet – The Resistance': 'https://open.spotify.com/track/5O9Dz0h08LuBi0aVvDcylh',
  'Pendulum feat. Steven Wilson – The Fountain': 'https://open.spotify.com/track/5blXK1R7GYL7gY2PVGxC90',
  'Mumford & Sons – The Cave': 'https://open.spotify.com/track/2HRpLui16GCENLFDXrnNkO',
  'Alcest – Autre Temps': 'https://open.spotify.com/track/50dpeks48j0zMECIKVAGUG',
  'Porcupine Tree – Trains': 'https://open.spotify.com/track/6BSMFkjxpazoEj0hJG5trT',
  'Kygo – Remind Me To Forget': 'https://open.spotify.com/track/6xTU6B6nFwKKTSZ9ySXS80',
  'Eleventyseven – Neverafter': 'https://open.spotify.com/track/4QubRWsmTAf2QX1yNaaxca',
  'Within Temptation – A Demon’s Fate': 'https://open.spotify.com/track/6UsQsPIPP7gjdtlISXx3F2',
  'Within Temptation – Restless': 'https://open.spotify.com/track/3BwU2MOfODibVdFDjOW63r',
  'Editors – Papillon': 'https://open.spotify.com/track/7hYiX6LMP8w8d0kEc4KWuW',
  'Lana del Rey – Young and Beautiful': 'https://open.spotify.com/track/2nMeu6UenVvwUktBCpLMK9',
  'Muse – Sunburn': 'https://open.spotify.com/track/5wq8wceQvaFlOZovDtfr0j',
  'Muse – Starlight': 'https://open.spotify.com/track/3skn2lauGk7Dx6bVIt5DVj',
  'Dragonforce – Through the Fire and Flames': 'https://open.spotify.com/track/1UMdbkqX19OiwfExH7gzYA',
  'Sonata Arctica – Don’t Say A Word': 'https://open.spotify.com/track/6khWZRJMRkIL6sZIeogVYn',
  'Owl City – On the Wing': 'https://open.spotify.com/track/3c13ucL6ziDiGD68rqoBNF',
  'Sunscreem vs Push – Please Save Me': 'https://open.spotify.com/track/1KhA5NKOeCeLOE39QLPnjc',
  'Owl City – The Saltwater Room': 'https://open.spotify.com/track/2tZIVD0ZPxpsoFx7hvAjWh',
  'Nightwish – Elan': 'https://open.spotify.com/track/5oAvb7LpUBwQfBtQ6hmS4Q',
  'Talco – Danza dell’autumno rosa': 'https://open.spotify.com/track/2d935rfyimiDOD1ghZssI1',
  'Sonata Arctica – Full Moon': 'https://open.spotify.com/track/2OcgUwz7uomyLpOi0juero',
  'Afrojack feat. Eva Simons – Take Over Control': 'https://open.spotify.com/track/5DdDbJvoaT8fqQMJkiGg4T',
  'Marillion – Seasons End': 'https://open.spotify.com/track/4LEgpPSyqlcMVsnMGnz1fD',
  'Eluveitie – Brictom': 'https://open.spotify.com/track/4yM6mWWdCiJu9NPUDmSryS',
  'Stromae – Papaoutai': 'https://open.spotify.com/track/34dx8DACTJsc3rsJdaEIQw',
  'Tori Amos – Winter': 'https://open.spotify.com/track/60J421Rq8u1HbUf8r2629k',
  'City to City – The Road Ahead': 'https://open.spotify.com/track/0MGMHRiLmoAurQLfKRKpcG',
  'Kodaline – Follow Your Fire': 'https://open.spotify.com/track/5ESJINHtOXLh3KSsazEfRf',
  'Epica – Reverence': 'https://open.spotify.com/track/5LgxqmlWRgKzc3juZJE7eR',
  'Coldplay – Trouble': 'https://open.spotify.com/track/0R8P9KfGJCDULmlEoBagcO',
  'Enter Shikari – Destabilise': 'https://open.spotify.com/track/01oP3GwVTTI8jBZnsuEzr3',
  'Family of the Year – Hero': 'https://open.spotify.com/track/1B10XgaxSXRLAFq967oMpF',
  'Tame Impala – The Less I Know The Better': 'https://open.spotify.com/track/6K4t31amVTZDgR3sKmwUJJ',
  'Rise Against – Under the Knife': 'https://open.spotify.com/track/7ycK2uijskzxp4cGpGNoCi',
  'Hurts – The Water': 'https://open.spotify.com/track/2akzuYCD9jaKKobiFrKLNA',
  'Foster The People – Houdini': 'https://open.spotify.com/track/5Fli1xRi01bvCjsZvKWro0',
  'Mark Knopfler – What It Is': 'https://open.spotify.com/track/7K3k5x1EZAtsqdp1CX1XKi',
  'We Came As Romans – Understanding What We’ve Grown To Be': 'https://open.spotify.com/track/7JTVQkaVsJF84WlfGDoUGU',
  'Alt-J – Breezeblocks': 'https://open.spotify.com/track/1ZLroqJA8qoS5QEeCo0fA7',
  'Mumford & Sons – Dust Bowl Dance': 'https://open.spotify.com/track/6rTdwouO3A55SjIjuiECic',
  'Cradle of Filth – Nymphetamine Fix': 'https://open.spotify.com/track/6WuqJLVZcyJklg7lIozAO8',
  'Keane – Silenced By The Night': 'https://open.spotify.com/track/0BhGZmaQ1SET53qGkGvwxD',
  'Marshmello & CHVRCHES – Here With Me': 'https://open.spotify.com/track/2jpKZFnBk98Ud3EoZiBOTf',
  'The Decemberists – Here I Dreamt I Was An Architect': 'https://open.spotify.com/track/1UyYuaCxOF4ilkRDZ74nJW',
  'Kodaline – Honest': 'https://open.spotify.com/track/1DIg9155AY65dpR5Lf5Vg4',
  'Band of Horses – The Funeral': 'https://open.spotify.com/track/5lRzWDEe7UuedU2QPsFg0K',
  'Twenty One Pilots – Heathens': 'https://open.spotify.com/track/6vkS2KTb49T8ONg7wkD8Pg',
  'Stylerockerz – Keep Livin’ This Dream': 'https://open.spotify.com/track/3rBeqxb9Wod4TBz3qBIuxA',
  'Limp Bizkit – Boiler': 'https://open.spotify.com/track/1a3RarhRdrNSTEEERYEFJn',
  'Halsey – New Americana': 'https://open.spotify.com/track/6Xs7OKt6i0Ddq8B4M5Dgvr',
  'Dire Straits – Sultans of Swing': 'https://open.spotify.com/track/37Tmv4NnfQeb0ZgUC4fOJj',
  'Buffalo Tom – Taillights Fade': 'https://open.spotify.com/track/563DsQH9eRURJ0GUZIi2fI',
  'Simon & Garfunkel – The Boxer': 'https://open.spotify.com/track/76TZCvJ8GitQ2FA1q5dKu0',
  'Chvrches – Tether': 'https://open.spotify.com/track/4Lk0MdvFUg23bDA0pCTrxG',
  'Cirya – I’ve Got The Love': 'doesnt exist',
  'Enter Shikari – No Sleep Tonight': 'https://open.spotify.com/track/7t87sUN9PulbbAvF7Uxajd',
  'Blind Channel – Balboa': 'https://open.spotify.com/track/3flVpGy1w3hS9crR1XL5BK',
  'Volbeat – Cape Of Our Hero': 'https://open.spotify.com/track/5zWnVHt2qAA1DBLlbzesAf',
  'Girls in Hawaii – Guinea Pig': 'https://open.spotify.com/track/2h7sVwz46zjpYm1uZyenrv',
  'Delain – The Greatest Escape': 'https://open.spotify.com/track/3eSgzedvNKdWlQIXJZrCHT',
  'Yellowcard – Shadows and Regrets': 'https://open.spotify.com/track/0Hvbnz7IZbiaWg0UHucOIS',
  'Gigi d’Agostino – L’amour Toujours': 'https://open.spotify.com/track/52LJ3hyknOijCrE5gCD0rE',
  'Europe – The Final Countdown': 'https://open.spotify.com/track/3MrRksHupTVEQ7YbA0FsZK',
  'Sue the Night – The Big Picture': 'https://open.spotify.com/track/2jOJ5j69HE4MJCTt776x6S',
  'Green Day – Boulevard of Broken Dreams': 'https://open.spotify.com/track/1hwJKpe0BPUsq6UUrwBWTw',
  'Paceshifters – Davis': 'https://open.spotify.com/track/19AtwpdS4ukW7mgcbStqbn',
  'Gorki – Mia': 'https://open.spotify.com/track/1AvAl5fj5mhoLHVo0to1xr',
  'Red Hot Chilli Peppers – Snow': 'https://open.spotify.com/track/2aibwv5hGXSgw7Yru8IYTO',
  'Of Monsters and Men – Little Talks': 'https://open.spotify.com/track/2ihCaVdNZmnHZWt0fvAM7B',
  'Blind Channel – Happy Doomsday': 'https://open.spotify.com/track/1S4YtFEbKHda2byazJ2Jr8',
  'Coldplay – Talk': 'https://open.spotify.com/track/4wzt5Rrk3W98pHXAqutuJw',
  'Rondé – Underwater': 'https://open.spotify.com/track/12o2tk8IhIDUiv9wargB8M',
  'Steven Wilson – Objects Outlive Us: Objects: Meanwhile': 'https://open.spotify.com/track/22qwKZ1DzJgZRRnb6kYUGI',
  'The Gaslight Anthem – Keepsake': 'https://open.spotify.com/track/6jeLQdLqSvOOKGS8OPuACi',
  'Mumford & Sons – Broken Crown': 'https://open.spotify.com/track/1cQC7k1Z9SbMk32zmHturK',
  'Cyndi Lauper – True Colors': 'https://open.spotify.com/track/2A6yzRGMgSQCUapR2ptm6A',
  'Onyx – Right in the Night': 'doesnt exist',
  'Yellowcard – Holly Wood Died': 'https://open.spotify.com/track/6VuW7NZCTzpkjlOWrsJymO',
  'Half Moon Run – She Wants To Know': 'https://open.spotify.com/track/1t29e18N84JoZlKfSFKOdk',
  'Daft Punk – Contact': 'https://open.spotify.com/track/2KHRENHQzTIQ001nlP9Gdc',
  'My Chemical Romance – This Is How I Disappear': 'https://open.spotify.com/track/0rUNZQuYQvOz6A6zwyT6tM',
  'Limp Bizkit – Break Stuff': 'https://open.spotify.com/track/5cZqsjVs6MevCnAkasbEOX',
  'Lights – Speeding': 'https://open.spotify.com/track/0k4kiY86YyvLYRqQETwyXD',
  'Blur – Song 2': 'https://open.spotify.com/track/3GfOAdcoc3X5GPiiXmpBjK',
  'Eleventyseven – Inside Out': 'https://open.spotify.com/track/6r3NtYiUlrLeguWMNqHdMT',
  'Michel Fugain – Une Belle Histoire': 'https://open.spotify.com/track/5oxKrYimzs8AZp8lkoar6V',
  'The Haunted Youth – Gone': 'https://open.spotify.com/track/16c5aIUUaDlZlcOuruDAXc',
  'Evanescence – Bring Me To Life': 'https://open.spotify.com/track/0COqiPhxzoWICwFCS4eZcp',
  'Niels Geusebroek – Take Your Time Girl': 'https://open.spotify.com/track/3vbcCYLei5EmF60B3r8666',
  'Rondé – Be Mine': 'https://open.spotify.com/track/7GqsS485BuDKtkuKdAaiRq',
  'Paramore – Ignorance': 'https://open.spotify.com/track/47No93LxERvV6MtOAmQzHS',
  'Lights – Running With The Boys': 'https://open.spotify.com/track/0wL87Fd27L4ow9CoMDP9wI',
  'Within Temptation – Say My Name': 'https://open.spotify.com/track/6va0jBtVHm7x3Ez3DdDLcx',
  'X Japan – I.V.': 'https://open.spotify.com/track/1bGgiCE2E8RaP35iJEAkr0',
  'Eleventyseven – Redeem The Scene': 'https://open.spotify.com/track/07mOnFzLkPc4MRYYsW3t9o',
  'Gotye – Somebody That I Used To Know': 'https://open.spotify.com/track/62oaDoBveZxvZb94ziiMXi',
  'Aleeze – 1 More Night': 'https://open.spotify.com/track/4QEEMH4bNBRSqtwAGapSvF',
  'Maustetytöt – Jos mulla ei ois sua, mulla ei ois mitään': 'https://open.spotify.com/track/4isqhUp7UWzvZ89Kr3RAs5',
  'Blood Red Shoes – Light It Up': 'https://open.spotify.com/track/0EqenqWs6DCDD2fgZTEYSF',
  'Maan & Goldband – Stiekem': 'https://open.spotify.com/track/0kINWIY7BToJACjRzIOqsz',
  'Black Eyed Peas – Just Can’t Get Enough': 'https://open.spotify.com/track/3JA9Jsuxr4xgHXEawAdCp4',
  'Marvin Gaye – Sexual Healing': 'https://open.spotify.com/track/3VZmChrnVW8JK6ano4gSED',
  'Porter Robinson – Cheerleader': 'https://open.spotify.com/track/1ggsR5kCepKTW4F64bCFdV',
  'Scooter – Nessaja': 'https://open.spotify.com/track/5RGiyzMQrBQQwMRid7SE65',
  'Enter Shikari – Radiate': 'https://open.spotify.com/track/2N19KWqVNIZKLvbHSTM6Hk',
  'Eefje de Visser – Storm': 'https://open.spotify.com/track/4orcc1xBc4DJiQatgioXBo',
  'Years & Years – King': 'https://open.spotify.com/track/3AeicLnm55RqcXGBKYQolM',
  'Blood Red Shoes – Je Me Perds': 'https://open.spotify.com/track/5mK1NJ2jEqekjRuCOBQ882',
  'Chvrches – High Enough To Carry You': 'https://open.spotify.com/track/5Y6SK2R1ZTbYcui9tnCICH',
  'Ludovico Einaudi – Nuvole Bianche': 'https://open.spotify.com/track/3weNRklVDqb4Rr5MhKBR3D',
  'Alphaville – Forever Young': 'https://open.spotify.com/track/4S1VYqwfkLit9mKVY3MXoo',
  'Tame Impala – Reality In Motion': 'https://open.spotify.com/track/3I7OmVsk4Hm5LBbs2GmhlD',
  'Scorpions – Wind of Change': 'https://open.spotify.com/track/3ovjw5HZZv43SxTwApooCM',
  'Hillsong United – Oceans': 'https://open.spotify.com/track/0Bn1DSXfisvfKjGUwI6rzW',
  'Owl City – Meteor Shower': 'https://open.spotify.com/track/2e4XYWpwydaH6WVFWQqrQ4',
  'Delain – We Are The Others': 'https://open.spotify.com/track/6uKvnGeg6xgzPTH3QSPTB6',
  'Deep Purple – Child in Time': 'https://open.spotify.com/track/4KFNmMV1tXCobxrtP9v8Yw',
  'Bubbles – Somewhere': 'https://open.spotify.com/track/2V56zaHCftB83E9EOwabno',
  'Within Temptation – Angels': 'https://open.spotify.com/track/4QWLhGVitrCCysR3ugX9Xw',
  'Half Moon Run – Need It': 'https://open.spotify.com/track/06bp6mIqFstXamxGpqWyyo',
  'The Cure – A Forest': 'https://open.spotify.com/track/4iVTSRiJAA18d3QglhyJ6Q',
  'Twenty One Pilots – Neon Gravestones': 'https://open.spotify.com/track/0sXvjZV7p4uvyPN4uQo3FH',
  'Eleventyseven – The Best I Can': 'https://open.spotify.com/track/5N2ThOsxDGuTbnkrYB2G1y',
  'The War on Drugs – Under the Pressure': 'https://open.spotify.com/track/5j58jhAFzAy0keSuQYsQBn',
  'The Shins – New Slang': 'https://open.spotify.com/track/1wAqhAF1dynDjMy7m5CSSE',
  'Editors – Sugar': 'https://open.spotify.com/track/2az3iTNyJ1M1JJnsU2Gq6H',
  'Fleetwood Mac – Sara': 'https://open.spotify.com/track/0q1exbzIDRxqJ6VUKH3seg',
  'Underoath – Wake Me': 'https://open.spotify.com/track/4ngmPsWsDJscbFedc1vZD2',
  'Sonata Arctica – Respect The Wilderness': 'https://open.spotify.com/track/5v0iliPDqvh6IplULiV5to',
  'Sexion d’Assaut – Avant Qu’elle Parte': 'https://open.spotify.com/track/53J0MZswXsuJfgG6kR3m32',
  'Steven Wilson & Ninet Tayeb – Pariah': 'https://open.spotify.com/track/7CcaktZZsdb8AWPdhDM38f',
  'Delain – Burning Bridges': 'https://open.spotify.com/track/0Z1I9iJRUkQPWGmrrkom3H',
  'Of Verona – Raining': 'https://open.spotify.com/track/0owxltXopgw4WQZGPRE7sU',
  'Swifty – Dakterras': 'https://open.spotify.com/track/0hHrAELMxVFpqdS757kRZL',
  'Rammstein – Mein Teil': 'https://open.spotify.com/track/39RKlCfLoqb8o2aXfpVfjW',
  'Babylon Zoo – Spaceman': 'https://open.spotify.com/track/0uQcP7QVoLvaFsORsdrgNh',
  'Delain – No Compliance': 'https://open.spotify.com/track/1xD9OdbNwWjsRbhA579Bc8',
  'DeWolff – Everything Everywhere': 'https://open.spotify.com/track/01fG4ULGbRBI62trSe4be1',
  'Beach House – Space Song': 'https://open.spotify.com/track/1ZgMsA55GIY7ICkQh5MILA',
  'Lights – Oil and Water': 'https://open.spotify.com/track/0IrIsWdmOjJo9QiaiXvyEE',
  'Beach House – Wild': 'https://open.spotify.com/track/23nIqNfEOOoTJaOfGjbRw5',
  'Melanie – Ruby Tuesday': 'https://open.spotify.com/track/6vr1sLoeL987BxGJW7XYaZ',
  'Paramore – Misery Business': 'https://open.spotify.com/track/3l9CW99AHtExIRV4hW2N5m',
  'Sinéad O’Connor – Troy': 'https://open.spotify.com/track/4ZbrvxwWPNX0MgbubsqbZG',
  'Dub FX – Intro': 'https://open.spotify.com/track/3mbDRVFKaOu2vHxiMQT89I',
  'Johnny Marr – Day in Day Out': 'https://open.spotify.com/track/24MrdAe7P4SNBtmkNEXwSW',
  'Marion Raven – For You I’ll Die': 'https://open.spotify.com/track/0bDdcWRhdD71DoiyoSK4Vo',
  'TheFatRat – Monody': 'https://open.spotify.com/track/4Rd5l7mIiV0V35AhxHV1oh',
  'Keane – Sovereign Light Café': 'https://open.spotify.com/track/4QRkCwqwHFaZ7xeoR9CHL6',
  'Sia – House On Fire': 'https://open.spotify.com/track/2dMmMkZ7SEqFbzTJx4DijY',
  'Talco – Dalla pallida miro': 'https://open.spotify.com/track/1RsYcFpHe5rKVqIpgELWVj',
  'DJ Sakin – I Cried For Her': 'https://open.spotify.com/track/5kcupQsQdmnehksX8sfl5K',
  'Delain – See Me In Shadow': 'https://open.spotify.com/track/2eYaFdU5NJD5Eh7e4gUORy',
  'Frank Boeijen Groep – Kronenburg Park': 'https://open.spotify.com/track/5l0mUA4hwewx7cj8KzBGGE',
  'Linkin Park – The Emptiness Machine': 'https://open.spotify.com/track/1EDPVGbyPKJPeGqATwXZvN',
  'Master Blaster – Get Closer': 'https://open.spotify.com/track/77fUvsbSdM08wgWhWHBCr4',
  'Hurts – Help': 'https://open.spotify.com/track/34WAwYbOdw2bgL5K2zFVNR',
  'Green Day – 21 Guns': 'https://open.spotify.com/track/64yrDBpcdwEdNY9loyEGbX',
  'Alphaville – Big in Japan': 'https://open.spotify.com/track/3BZGi1yUqQyCNC868AqUGG',
  'Talco – All’adunata del feticcio': 'https://open.spotify.com/track/3kLDGfmUlhUBOx5QAvovYd',
  'Chipz – Ch!pz In Black': 'https://open.spotify.com/track/1maRB5Epd77jduOZxRkZ3j',
  'Arcade Fire – Reflektor': 'https://open.spotify.com/track/7uMZy0bALAdneerERyr7Ks',
  'The National – I Need My Girl': 'https://open.spotify.com/track/50M7nY1oQuNHecs0ahWAtI',
  'Zala & Gasper – Sebi': 'https://open.spotify.com/track/1kXDk1RaOZcIfxdQCVxMWK',
  'Alan Walker – Darkside': 'https://open.spotify.com/track/1snWlbcbgQpJfknoI30DWG',
  'Teddy Swims – The Door': 'https://open.spotify.com/track/3dj4wgM3cPeuLwMNHDuBon',
  'Sonata Arctica – My Land': 'https://open.spotify.com/track/3IwGCc9pW94ZoHA1aO0WiD',
  'Kensington – All For Nothing': 'https://open.spotify.com/track/5uC8a9FxdqJ59XHjzdibCf',
  'Anouk – Nobody’s Wife': 'https://open.spotify.com/track/1Q0p30HuN1ADMX2CmPzIvO',
  'Demon Hunter – More Than Bones': 'https://open.spotify.com/track/6YPopUgTLk3LaISL9cDAPm',
  'Meat Loaf – Original Sin': 'https://open.spotify.com/track/5ymDpMY5NT5ojunOx0IWuW',
  'Meat Loaf – For Crying Out Loud': 'https://open.spotify.com/track/0GD6Ug6ouPqkthlnT058aC',
  'Yellowcard – Breathing': 'https://open.spotify.com/track/0DxN6Ywom8nnndyQXdSBPy',
  'Within Temptation – Stand My Ground': 'https://open.spotify.com/track/7Chqf4yGnQlLWAWic9b0ET',
  'Scooter – The Night': 'https://open.spotify.com/track/1RkgwvQIrGFNdfHy3VYGhh',
  'Liquido – Narcotic': 'https://open.spotify.com/track/1H5VQuShs4qfwBXyHF0PeH',
  'Radiohead – Karma Police': 'https://open.spotify.com/track/63OQupATfueTdZMWTxW03A',
  'Ermal Meta – Non mi avete fatto niente': 'https://open.spotify.com/track/1oMYET9xQB8XpxwTt2c5Dz',
  'R.E.M. – Drive': 'https://open.spotify.com/track/3geRffSf6eAruhg23RkpKV',
  'The Joy Formidable – This Ladder Is Ours': 'https://open.spotify.com/track/2hqXTApLr4AY3R9kuyNU9v',
  'HIM – Join Me': 'https://open.spotify.com/track/5ooqCHqs4axSJbWqIHfKfB',
  'Foo Fighters – The Pretender': 'https://open.spotify.com/track/7x8dCjCr0x6x2lXKujYD34',
  'Sonata Arctica – Shy': 'https://open.spotify.com/track/1JKnXimBkpgfAeohZVLk3W',
  'Porcupine Tree – Lazarus': 'https://open.spotify.com/track/4xnztDfQLOzEBi5yxKAkhM',
  'Blur – The Universal': 'https://open.spotify.com/track/0qmCWYu7hOvriyuqXfPw7I',
  'Beast in Black – One Night In Tokyo': 'https://open.spotify.com/track/2TZtQt10Ajm3wB4MoqluZj',
  'Lordi – Hard Rock Hallelujah': 'https://open.spotify.com/track/7sZTvm0Sx8umbyQViTE2Qc',
  'Lasgo – Gone': 'https://open.spotify.com/track/1QfJwbwcWUHheqVo3yRfpd',
  'Porcupine Tree – Way Out Of Here': 'https://open.spotify.com/track/7I1BHtM3RNofV9CPvnMem3',
  'Kansas – Carry On Wayward Son': 'https://open.spotify.com/track/4DMKwE2E2iYDKY01C335Uw',
  'Lana del Rey – Video Games': 'https://open.spotify.com/track/7FDHI71Z3IInsEKuUn7Df8',
  'Dry the River – Lion’s Den': 'https://open.spotify.com/track/1NBXOfV3lQjfbWlKJn4323',
  'Delain – Frozen': 'https://open.spotify.com/track/5SYwjPPkPfedyy9HtTcBWi',
  'White Lies – Time To Give': 'https://open.spotify.com/track/3xFGQGWOVVkeSAVIrYtb9D',
  'Muse – Map of the Problematique': 'https://open.spotify.com/track/5YXr4AGfUQpLSxtFSsKUh6',
  'Claude – Ladada': 'https://open.spotify.com/track/0LVjBdjZvJykxed42ExTLf',
  'Beach House – Wildflower': 'https://open.spotify.com/track/44ZdzQCcGwjyweRELhs5qM',
  'The Wombats – Tokyo': 'https://open.spotify.com/track/0dt2bECwIUEzWppQLeUqG6',
  'Warpaint – Keep it Healthy': 'https://open.spotify.com/track/0YVUDMJ1OG8nKsU4sCqmkg',
  'Chvrches – Strong Hand': 'https://open.spotify.com/track/6QRyDxgiNSKYsR8CNlc2fZ',
  'Hurts – Better Than Love': 'https://open.spotify.com/track/6nbsaXBPuj2TWFS3GqgI4f',
  'Mozes and the Firstborn – Sad Supermarket Song': 'https://open.spotify.com/track/4jY3nrmw8tpKcvFZEqMkDJ',
  'Tame Impala – Borderline': 'https://open.spotify.com/track/5hM5arv9KDbCHS0k9uqwjr',
  'Zella Day – High': 'https://open.spotify.com/track/7wYrc3r17ExXnbzyFcvxwn',
  'Teddy Swims – Bad Dreams': 'https://open.spotify.com/track/3BntzKsnLf2pc0dsvE3Zav',
  'Bots – Menens': 'https://open.spotify.com/track/1eDwlp4gzasE833LzHzGfa',
  'Twenty One Pilots – Ode to Sleep': 'https://open.spotify.com/track/7wwsdetDpqdnajrqnhU50M',
  'Alt-J – Nara': 'https://open.spotify.com/track/1o5yGKORyYWpUOxnPLlSuh',
  'The Birthday Massacre – Kill The Lights': 'https://open.spotify.com/track/1SWKI3Ee9EHEAiTRHp1bCI',
  'Macklemore & Ryan Lewis – Can’t Hold Us': 'https://open.spotify.com/track/3bidbhpOYeV4knp8AIu8Xn',
  'Radiohead – Street Spirit': 'https://open.spotify.com/track/2QwObYJWyJTiozvs0RI7CF',
  'Blaudzun – Promises Of No Man’s Land': 'https://open.spotify.com/track/4kHbiBPkwJngFFYm04vMLW',
  'Gala – Freed From Desire': 'https://open.spotify.com/track/2y8wIiJ4w47qDmnkSEQ6f0',
  'Racoon – Lucky All My Life': 'https://open.spotify.com/track/53qOkWdrRJLFnBeMZadhj0',
  'Billie Eilish – Bad Guy': 'https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m',
  'Ma.Bra – Cursed Destiny': 'https://open.spotify.com/track/6qOerkTuX21awpMOhDOHrb',
  'The Pigeon Detectives – I’m Not Gonna Take This': 'https://open.spotify.com/track/33FBMIxXw1KpwUKQZFxgEQ',
  'The Overslept – Stolen Car': 'https://open.spotify.com/track/0dQZfCRbSjZwSQ2pQvEPyB',
  'Procol Harum – A Whiter Shade Of Pale': 'https://open.spotify.com/track/2ECReVEeiSQk8zpC9TRAwx',
  'Nirvana – Smells Like Teen Spirit': 'https://open.spotify.com/track/4CeeEOM32jQcH3eN9Q2dGj',
  'AWS – Viszlát Nyár': 'https://open.spotify.com/track/3o66uVdvTjFP4amNCiN9BI',
  'Alcest – Souvenirs d’un autre monde': 'https://open.spotify.com/track/1eD8fNbyfyXWrTLokilmEM',
  'Alt-J – Bloodflood, Pt. II': 'https://open.spotify.com/track/3WfWJIMqzxJjbMQQHEyG3P',
  'System of a Down – Chop Suey': 'https://open.spotify.com/track/2DlHlPMa4M17kufBvI2lEN',
  'Biffy Clyro – Biblical': 'https://open.spotify.com/track/5o1SyGe6l3EKbw0KiTQH2m',
  'Lazard – Little Star': 'https://open.spotify.com/track/3WACja45ORjzgSC0LJlqxq',
  'Sabaton – Ghost Division': 'https://open.spotify.com/track/1MoEyYsa9Y0FvApwLskO1l',
  'PPK – Resurrection': 'doesnt exist',
  'Twenty One Pilots – Stressed Out': 'https://open.spotify.com/track/3CRDbSIZ4r5MsZ0YwxuEkn',
  'Thirty Seconds to Mars – From Yesterday': 'https://open.spotify.com/track/1JBa9B1iA4yNVpJ5wVGrZH',
  'Twenty One Pilots – Holding On To You': 'https://open.spotify.com/track/116tP87VfGkCBFpS2mP5sv',
  'Toto – Africa': 'https://open.spotify.com/track/2374M0fQpWi3dLnB54qaLX',
  'Bowling for Soup – How Far This Can Go': 'https://open.spotify.com/track/7yu0OvHRf16FQ3A3mztOoa',
  'Bløf – Zoutelande': 'https://open.spotify.com/track/0le8EcVp4x1JjMhwRKIOVi',
  'DJ Quicksilver – Ameno': 'https://open.spotify.com/track/3okFUxgWC2RZ2DoTzjsKM5',
  'Meat Loaf – I’d Lie For You': 'https://open.spotify.com/track/0hrh211HEFDbqIpG6znlwQ',
  'The Script & Will.i.am – Hall of Fame': 'https://open.spotify.com/track/7wMq5n8mYSKlQIGECKUgTX',
  'Porcupine Tree – Anesthetize': 'https://open.spotify.com/track/2VvUor8pk8HOR9cb5iC84z',
  'Chvrches – The Mother We Share': 'https://open.spotify.com/track/31AyUvMRDvZjyQI1N05lsT',
  'Keane – Bedshaped': 'https://open.spotify.com/track/17xGX76BVzLRSbpYteAGR4',
  'Fleetwood Mac – Landslide': 'https://open.spotify.com/track/5ihS6UUlyQAfmp48eSkxuQ',
  'Krezip – Sweet Goodbyes': 'https://open.spotify.com/track/4NH0G33zApUnRNsSK0CwuN',
  'All Time Low – Weightless': 'https://open.spotify.com/track/0aZJGkkXR3DgaFqo5sB8ot',
  'Snelle – Reünie': 'https://open.spotify.com/track/0C9JPibPAdaBvt60rbwEsJ',
  'Sum 41 – Screaming Bloody Murder': 'https://open.spotify.com/track/1zqAXXA12UEVS7iDmAVeay',
  'Editors – Bricks and Mortar': 'https://open.spotify.com/track/3y5JP4RkzCfIS334e94vIo',
  'Electric Callboy – Pump It': 'https://open.spotify.com/track/6emZMVNvIxW57fhxPlyxLp',
  'Sonata Arctica – Talullah': 'https://open.spotify.com/track/6dOtVTDdiauQNBQEDOtlAB',
  'Billie Eilish – Birds of a Feather': 'https://open.spotify.com/track/33F4l7xj1cEeiqyUCfHlvw',
  'Lights – How We Do It': 'https://open.spotify.com/track/5oShqZVx6tnghm4cUKQeKS',
  'Nightwish – Nemo': 'https://open.spotify.com/track/6zfgRJKADV9DsroQBNwmBI',
  'Nightwish – Amaranth': 'https://open.spotify.com/track/1sXdW94CrEIrYdbfON4Sxt',
  'Smash Mouth – All Star': 'https://open.spotify.com/track/2P1ZqQq8rQtmV7BLZ0Junn',
  '30 Seconds to Mars – Attack': 'https://open.spotify.com/track/0lHSJ0ZP8uUPnJXhMdGjOK',
  'Marco Borsato – Nooit Meer Een Morgen': 'https://open.spotify.com/track/0dJQx5qp3HJ68crwVMK78E',
  'The Connells – ’74-‘75': 'https://open.spotify.com/track/2MAVcVr2oylw2OZ3hojWYj',
  'The National – Bloodbuzz Ohio': 'https://open.spotify.com/track/5idVbYWHOBsFktyGq9KhkL',
  'Blood Red Shoes – In Time To Voices': 'https://open.spotify.com/track/0UC6JYEePZGefuQaGtFxa2',
  'Coldplay – Speed of Sound': 'https://open.spotify.com/track/7clUVcSOtkNWa58Gw5RfD4',
  'Douwe Bob – Was It Just Me': 'https://open.spotify.com/track/5HiHK2jxYRvFZnIo6WujwQ',
  'Passenger – Let Her Go': 'https://open.spotify.com/track/5kWcIgj5CszKQBB0Lg7sGY',
  'Green Day – Holiday': 'https://open.spotify.com/track/5vfjUAhefN7IjHbTvVCT4Z',
  'Basshunter – Boten Anna': 'https://open.spotify.com/track/3N9huFk2IceMSlKoZLaUsv',
  'Kaiser Chiefs – Oh My God': 'https://open.spotify.com/track/24KqWcpyrY1COcRPYt2ef5',
  'Like Torches – Missing It All': 'https://open.spotify.com/track/3U59dRvyhyMedTsZxqdPwm',
  'Eefje de Visser – De Parade': 'https://open.spotify.com/track/63i8rEP5gnpHwRF3ieyzxp',
  'Arch Enemy – Reason To Believe': 'https://open.spotify.com/track/02gIPDHCTuKgKEl2VlgPzt',
  'D-JMC feat. Beatmonique – You May Think': 'https://open.spotify.com/track/6EzSy7WxNCazx3csu7lxdV',
  'The Script – If You Could See Me Now': 'doesnt exist',
  'Pinball – Make it Happen': 'https://open.spotify.com/track/5GS8mEdxNl0IsOLtOUFkB6',
  'Placebo – Beautiful James': 'https://open.spotify.com/track/0SUMFBC9EV9dCgEMUy6ImI',
  'M83 – Atlantique Sud': 'https://open.spotify.com/track/0Oxi3c2s1Lg96MgL9ZDsMR',
  'The War on Drugs – Strangest Thing': 'https://open.spotify.com/track/413CBplTN03RNZD8H34B6q',
  'Too Many Outs – I Like To Think': 'https://open.spotify.com/track/2sW7GXnNRn0qbMJ6bdl6F1',
  'Sigur Rós – Untitled #8': 'https://open.spotify.com/track/0juwzpu354078dcKpR5p0w',
  'Blood Red Shoes – It’s Getting Boring By The Sea': 'https://open.spotify.com/track/6hs6hpFoWxibLxTPklD6tR',
  'Nelly Furtado – Try': 'https://open.spotify.com/track/5uh5sS1edSvfQxRvtCgT4N',
  'Hurts – Unspoken': 'https://open.spotify.com/track/0TgQCOlcdDDxSvaJ84cAY5',
  'Blind Channel – Dark Side': 'https://open.spotify.com/track/1ovFnZv6mUe0LzAbfVqOmh',
  'Groove Coverage – Lullaby for Love': 'https://open.spotify.com/track/3oyydehLWRBruTQoTB3MFh',
  'Day After Tomorrow – Starry Heavens': 'https://open.spotify.com/track/1EtO6ISIcgeNjSJY1k7YMd',
  'Beast in Black – Oceandeep': 'https://open.spotify.com/track/5olj6v9yUiolgkmKHOhIkI',
  'The Prodigy – Voodoo People': 'https://open.spotify.com/track/7C0PzxbsQx59DgGVRsquwJ',
  'Muse – The 2nd Law: Unsustainable': 'https://open.spotify.com/track/21lhern14mW8gwK2oOqMbP',
  'Radiohead – No Surprises': 'https://open.spotify.com/track/10nyNJ6zNy2YVYLrcwLccB',
  'Johnny Marr – Hi Hello': 'https://open.spotify.com/track/1NVksWXj48VGjHx11NNASj',
  'Temples – Colours To Life': 'https://open.spotify.com/track/1SrdKbwjC2XOptogQc6luY',
  'Chvrches – Warning Call': 'https://open.spotify.com/track/3vVYHLjVOXa0EQl4G34pLm',
  'My Chemical Romance – Welcome To The Black Parade': 'https://open.spotify.com/track/5wQnmLuC1W7ATsArWACrgW',
  'Steve Harley & Cockney Rebel – Sebastian': 'https://open.spotify.com/track/2IyzwzJVyBOBmqmW3s8mrb',
  'Lana del Rey – Summertime Sadness': 'https://open.spotify.com/track/33CeM8NI7tfrNgciVOFMoo',
  'Sia – Snowman': 'https://open.spotify.com/track/7uoFMmxln0GPXQ0AcCBXRq',
  'Eefje de Visser – Startschot': 'https://open.spotify.com/track/5TYnWTit6kBSCJ3AfFZtJv',
  'Delain – Chemical Redemption': 'https://open.spotify.com/track/3oRCgaudoeZsG4VfJROlez',
  'Coldplay – Charlie Brown': 'https://open.spotify.com/track/1yqMgZNrevsWMLWfO2PRp5',
  'Danny Vera – Roller Coaster': 'https://open.spotify.com/track/5B5YKjgne3TZzNpMsN9aj1',
  'Epica – Beyond the Matrix': 'https://open.spotify.com/track/3Pv2hxfACvClA6ufdOEbYQ',
  'Blood Red Shoes – I Wish I Was Someone Better': 'https://open.spotify.com/track/0KqCivRG1BH1vUZO04AHXT',
  'Neil Young – Heart of Gold': 'https://open.spotify.com/track/5vd1QZ0tdXOExiegC55IAS',
  'Epica – Unchain Utopia': 'https://open.spotify.com/track/0KH0Ox65pRJ4F2kCDrm3gt',
  'Rondé – We Got It': 'https://open.spotify.com/track/3suDoAXX6otxz0WBMHc6pp',
  'Eleventyseven – Kick the Habit': 'https://open.spotify.com/track/2LjnYb14UxsGNkZ2TqSKVQ',
  'Mägo de Oz – La Costa del Silencio': 'https://open.spotify.com/track/4mTsRdFE28MYlrZo8N4Es0',
  'All Time Low – Backseat Serenade': 'https://open.spotify.com/track/47eL0bckn5g3k5VBwgu969',
  'Alex Megane – Hurricane': 'https://open.spotify.com/track/2d5xNJtCgefH0I1koYyLX5',
  'Cradle of Filth – The Death of Love': 'https://open.spotify.com/track/0wkscODHkDKzOU21rIgHy2',
  'Mumford & Sons – Below My Feet': 'https://open.spotify.com/track/7AdnuwqXfe8bKB8Hr8T51e',
  'Editors – The Racing Rats': 'https://open.spotify.com/track/1VCxGwTx1F4I7hvMJPV2ip',
  'Clouseau – Passie': 'https://open.spotify.com/track/34oyuLfWrmAPXENXDa9kvX',
  'De Jeugd van Tegenwoordig – Sterrenstof': 'https://open.spotify.com/track/7D5vAulNfrQV6xEwzgH0OF',
  'Marco Borsato – De Bestemming': 'https://open.spotify.com/track/78vBe7yQRROyT42PzT5Xpm',
  'Mànran – Oran Na Cloiche': 'https://open.spotify.com/track/4oNJi8OfbewGyw1VGne3l4',
  'Kristina – Horehronie': 'https://open.spotify.com/track/012d7d7oRmXrqrZWtHakom',
  'Symphony X – Paradise Lost': 'https://open.spotify.com/track/22sEfJxatkWlGVsqWKhtvY',
  'The Smiths – Bigmouth Strikes Again': 'https://open.spotify.com/track/2OErSh4oVVAUll0vHxdr6p',
  'All Time Low – A Love Like War': 'https://open.spotify.com/track/0TPF6uW7fhMXJPoBERqTy5',
  'Leonard Cohen – You Want It Darker': 'https://open.spotify.com/track/5zb7npjQqoJ7Kcpq4yD9qn',
  'C-Bool – Would You Feel': 'https://open.spotify.com/track/3EC2WlIrRBZqN8kPH1qNTd',
  'Panic! At the Disco – Casual Affair': 'https://open.spotify.com/track/2zkXavDV9dw8uR0pfhsBt2',
  'MGMT – Kids': 'https://open.spotify.com/track/1jJci4qxiYcOHhQR247rEU',
  'Billy Talent – Fallen Leaves': 'https://open.spotify.com/track/3jUTjCISntIUFL8jnAjzgc',
  'Pennywise – Bro Hymn': 'https://open.spotify.com/track/1ybhXkz4S8k9fdBZNBan7L',
  'Linkin Park – One Step Closer': 'https://open.spotify.com/track/3K4HG9evC7dg3N0R9cYqk4',
  'Marco Borsato – Als rennen geen zin meer heeft': 'https://open.spotify.com/track/5212Uuk27IRh9uijTMoCAS',
  'Skrillex – Scary Monsters And Nice Sprites': 'https://open.spotify.com/track/5q8oybjZelukF4h0CzSUN9',
  'Muse – Micro Cuts': 'https://open.spotify.com/track/2GflWmANujk7PnmEcv5RbF',
  'Hurts – Miracle': 'https://open.spotify.com/track/0s28qR4TvOmbHZwKzkeeRj',
  'We Came As Romans – Hope': 'https://open.spotify.com/track/4JFUKD0b2V6IiW1up71GqU',
  'Ellie Goulding – Burn': 'https://open.spotify.com/track/2GgxS8bUT5G25QJTsfSv0R',
  'De Kast – In Nije Dei': 'https://open.spotify.com/track/0sn7dop3MyxuSj281NwxWF',
  'Alestorm – Keelhauled': 'https://open.spotify.com/track/2FBmddNjVLziN4AxfUmdQe',
  'Nightmare – The World': 'https://open.spotify.com/track/5W53797BOyrbASWrZq24lp',
  'Kate Bush – Wuthering Heights': 'https://open.spotify.com/track/5YSI1311X8t31PBjkBG4CZ',
  'Niviro – Life In Reverse': 'https://open.spotify.com/track/0yPFuWtbg4rQfz7aJJe4jF',
  'Eminem – Cleaning Out My Closet': 'https://open.spotify.com/track/7BMO7O7ImjV8HNTH74Tshv',
  'Apollo – Dance': 'https://open.spotify.com/track/69kLQpfT8qpduZd8vVRXTg',
  'The Smiths – Some Girls Are Bigger Than Others': 'https://open.spotify.com/track/3znapZvsInnCVsDERDUaM5',
  'Sefa – Sisyphus': 'https://open.spotify.com/track/1drrKVyPc1gwP1ykPo6QdW',
  'East Rockerz – Sound Of My Dream': 'doesnt exist',
  'Rammstein – Deutschland': 'https://open.spotify.com/track/2bPGTMB5sFfFYQ2YvSmup0',
  '3 Doors Down – Kryptonite': 'https://open.spotify.com/track/6ZOBP3NvffbU4SZcrnt1k6',
  'Foo Fighters – My Hero': 'https://open.spotify.com/track/4dVbhS6OiYvFikshyaQaCN',
  'The Rasmus – Jezebel': 'https://open.spotify.com/track/2NehRqeFiEGV72lFfqJGUn',
  'Eros Ramazzotti – Cose Della Vita': 'https://open.spotify.com/track/7L93Qjqgh05ZuFflWWyTjN',
  'Enter Shikari – Enter Shikari': 'https://open.spotify.com/track/5cxKbYUSxcbURHH7zbfE14',
  'Nada Surf – Popular': 'https://open.spotify.com/track/48sJGpBLqQTs0sZ2ImHJof',
  'Eleventyseven – Ghost': 'https://open.spotify.com/track/17d3mVFcwvgdtinQvV6WG1',
  'Nightwish – Edema Ruh': 'https://open.spotify.com/track/5ql1bMU3X5NYamBDMVEdJc',
  'Nick Skitz & Technoposse – Call From Babylon': 'https://open.spotify.com/track/2nRY3wt2sOxXdMyV11LAhb',
  'Sita – Happy': 'https://open.spotify.com/track/2G8czBYoqbDYj9C9bks1P8',
  'The Jellyrox – Someone Else': 'https://open.spotify.com/track/3siDkvu34VF7tDrngX8cBr',
  'Kompulsor – Look At Me Now': 'https://open.spotify.com/track/73jpDET1V3V9Nuz1r2tQej',
  'Eleventyseven – Divers in a Hurricane': 'https://open.spotify.com/track/2N6K2K3gq7Neyrs7LA1hyB',
  'ABBA – The Day Before You Came': 'https://open.spotify.com/track/6W26h4KbGUnEaav5VWIyJm',
  'Sia – Broken Glass': 'https://open.spotify.com/track/22iKiimk9wEJWdHlKdtFsA',
  'Tame Impala – Yes I’m Changing': 'https://open.spotify.com/track/0xtIp0lgccN85GfGOekS5L',
  'Neo Cortex – I Want You': 'https://open.spotify.com/track/24U7NbCLeYJyG3OFdfymYB',
  'Eminem – Legacy': 'https://open.spotify.com/track/1mavQ4WCzXSeL2Dm5DS4GQ',
  'Dub FX – Run': 'https://open.spotify.com/track/4Epwg1ZNyD4LoXVeCBSYFY',
  'Arctic Monkeys – I Bet You Look Good On The Dancefloor': 'https://open.spotify.com/track/3DQVgcqaP3iSMbaKsd57l5',
  'Arcade Fire – The Suburbs': 'https://open.spotify.com/track/2UWdUez9MB9yzL7Y81Mcip',
  'Within Temptation – Where is the Edge': 'https://open.spotify.com/track/2UqvNtxruIlQbUWz4bhT89',
  'Half Moon Run – Full Circle': 'https://open.spotify.com/track/0gr60jINHbKdcGlQ83rmaH',
  'Flemming – Paracetamollen': 'https://open.spotify.com/track/0bSgNta3s0kIZkxuBI9PxR',
  'Skillet – Hero': 'https://open.spotify.com/track/4CbKVDZkYKdv69I4bCaKUq',
  'Wes – Alane': 'https://open.spotify.com/track/2wkoeulxiywQoKtniBbTHJ',
  'The Bigger Lights – Never Mistake A Suit For A Friend': 'doesnt exist',
  'Dua Lipa – Houdini': 'https://open.spotify.com/track/6D8y7Bck8h11byRY88Pt2z',
  'Enter Shikari – Quelle Surprise': 'https://open.spotify.com/track/74wT8UifPGs13pZQdACJOG',
  'Rage Against The Machine – Killing In The Name Of': 'https://open.spotify.com/track/59WN2psjkt1tyaxjspN8fp',
  'Elevation Worship – Here As In Heaven': 'https://open.spotify.com/track/0fPwregqch9wLJj4yQH6Bk',
  'Shantel – Disko Partizani': 'https://open.spotify.com/track/3ACn6cRxktkPT3HGKX1ZTz',
  'Phil Collins – Two Hearts': 'https://open.spotify.com/track/2BgWv15eKCDfiubKo6o76k',
  'Yellowcard – Five Becomes Four': 'https://open.spotify.com/track/2REfznWvZEa7eT9VUpxIqn',
  'Taylor Swift – We Are Never Ever Getting Back Together': 'https://open.spotify.com/track/0VwNdo84DaVYLIkbVO86ND',
  'Beast in Black – Sweet True Lies': 'https://open.spotify.com/track/2cyJkqB2OYHwWWvKGtrJ0r',
  'Rammstein – Du Hast': 'https://open.spotify.com/track/5awDvzxWfd53SSrsRZ8pXO',
  'Blur – Parklife': 'https://open.spotify.com/track/3mqRLlD9j92BBv1ueFhJ1l',
  'Bowling for Soup – Turbulence': 'https://open.spotify.com/track/6JzaqoCylWyaS7YFp5hF0n',
  'Placebo – The Never-Ending Why': 'https://open.spotify.com/track/0TOaZ47wURRYdw6e9OLELE',
  'Nightwish – The Poet and the Pendulum': 'https://open.spotify.com/track/5sDDSdsBa15i2IDhJ7HsYV',
  'Warpaint – Love is to Die': 'https://open.spotify.com/track/2RAXAF7qjvn0FsRuMMTlBx',
  'Demon Hunter – I Don’t Believe You': 'https://open.spotify.com/track/1oGYcEm47JD3xKpVrjM6nl',
  'Arctic Monkeys – Do I Wanna Know?': 'https://open.spotify.com/track/5FVd6KXrgO9B3JPmC8OPst',
  'Eefje de Visser – Bitterzoet': 'https://open.spotify.com/track/39He9xYIIOdK0pU3U9OjAs',
  'Ian van Dahl – Castles in the Sky': 'https://open.spotify.com/track/3uMZMYC0GurzpeTf9QvPe0',
  'Coldplay – Hymn For The Weekend': 'https://open.spotify.com/track/3RiPr603aXAoi4GHyXx0uy',
  'Owl City – The Tip of the Iceberg': 'https://open.spotify.com/track/4GJvgLicVBUAiitZAsQ5pf',
  'Andy Burrows – Hometown': 'https://open.spotify.com/track/1nJntmdlEvCfQar5fDveCu',
  'Arcade Fire – Rebellion': 'https://open.spotify.com/track/0xOeB16JDbBJBJKSdHbElT',
  'Muse – Bliss': 'https://open.spotify.com/track/0j3obufLXq5toSs592dX9U',
  'Alex Megane – Stars': 'https://open.spotify.com/track/3tpJWP7ZtUtCkszZ6aivRt',
  'Noah and the Whale – L.I.F.E.G.O.E.S.O.N.': 'https://open.spotify.com/track/6DDoFN7yNQmL2YXojqAk8S',
  'Blanks – Bittersweet': 'https://open.spotify.com/track/6dtd7jjjz2tZ1A4bjGshpO',
  'Cascada – Everytime We Touch': 'https://open.spotify.com/track/5YJtMNWKe55yr49cyJgxva',
  'Rondé – Why Do You Care': 'https://open.spotify.com/track/3oDn64B3LsqBfcvQA5UJrh',
  'Kate Bush – Rubberband Girl': 'https://open.spotify.com/track/0BYdxsa0Ct2GH83cNaEkq1',
  'Mumford & Sons – After The Storm': 'https://open.spotify.com/track/7HdBUO6EWiFDXNabcUReba',
  'Cyndi Lauper – Girls Just Wanna Have Fun': 'https://open.spotify.com/track/459EpH5UZgE6fMNPMLOgMF',
  'Within Temptation – Stairway to the Skies': 'https://open.spotify.com/track/6Q3kathPO8kg7vA1BS5d9y',
  'Yannick Noah – Destination Ailleurs': 'https://open.spotify.com/track/3jA3fdVnnUb465RbTwzgbK',
  'Arctic Monkeys – When The Sun Goes Down': 'https://open.spotify.com/track/2zzLRQ78kKfPTx8FJQCdC2',
  'Nightwish – Shudder Before The Beautiful': 'https://open.spotify.com/track/50CJMURkzURQwlp4Ht5tp6',
  'Toby – Leave The World Behind': 'doesnt exist',
  'The Haunted Youth – In My Head': 'https://open.spotify.com/track/2Z8fMSm0LojIUwDeQqykKR',
  'Evanescence – My Immortal': 'https://open.spotify.com/track/4UzVcXufOhGUwF56HT7b8M',
  'Porcupine Tree – Open Car': 'https://open.spotify.com/track/3p3YCGXfHzWYbMn6Q07zYQ',
  'Plain White T’s – Hey There Delilah': 'https://open.spotify.com/track/3DWOTqMQGp5q75fnVsWwaN',
  'Meat Loaf – I’d Do Anything For Love': 'https://open.spotify.com/track/4UrgDocbHywDZv2f3mBhCq',
  'Too Many Outs – Hell of a Day': 'https://open.spotify.com/track/4nOhgK8AlpF2NoHR43Nxdd',
  'Pearl Jam – Just Breathe': 'https://open.spotify.com/track/6i81qFkru6Kj1IEsB7KNp2',
  'Eminem – Bad Guy': 'https://open.spotify.com/track/3IaAYtmN8T0YIYVqnxNnVz',
  'Steven Wilson & Ninet Tayeb – Routine': 'https://open.spotify.com/track/5cxmpBhMn4Wxs4ZyHLv4mR',
  'Of Verona – Zero Gravity': 'https://open.spotify.com/track/2DEbtCkWCYxBYL8iNlMh4O',
  'Fields of the Nephilim – And There Will Your Heart Be Also': 'https://open.spotify.com/track/00Lx2f8NRiFKMGWa0GBGEt',
  'Keane – Everybody’s Changing': 'https://open.spotify.com/track/0yac0FPhLRH9i9lOng3f81',
  'Rammstein – Ich Will': 'https://open.spotify.com/track/3X0K6fII7VIwL1URPrp8Ko',
  'Owl City – Peppermint Winter': 'https://open.spotify.com/track/7MqDwR9yskBfZCybiNKlef',
  'BoA – Every Heart': 'https://open.spotify.com/track/4RfCsOwpRM4zQv24IXFmEG',
  'Muse – Uprising': 'https://open.spotify.com/track/4VqPOruhp5EdPBeR92t6lQ',
  'Bring Me The Horizon – Can You Feel My Heart': 'https://open.spotify.com/track/0WSa1sucoNRcEeULlZVQXj',
  'Opeth – Coil': 'https://open.spotify.com/track/3P0LXXybFHgu2aY1NyGViV',
  'Coldplay – A Sky Full of Stars': 'https://open.spotify.com/track/0FDzzruyVECATHXKHFs9eJ',
  'Delain – We Had Everything': 'https://open.spotify.com/track/1WmwnPrHhBk303bycwEdML',
  'Lights – Lucky Ones': 'https://open.spotify.com/track/4Z1e62tPdgCAKcjWZD0em7',
  'Nahko & Medicine for the People – Love Letters To God': 'https://open.spotify.com/track/6ifhHUZ6saBxf66BVC8acE',
  'The Vaccines – Post Break-Up Sex': 'https://open.spotify.com/track/47oXAoC5TynVLCZ3FKb0gC',
  'Tame Impala – Endors-Toi': 'https://open.spotify.com/track/0YuePEX4KyfLIPMdNLPwgQ',
  'Halsey – Eyes Closed': 'https://open.spotify.com/track/0IYzTSQj0G21K2ZDSwUZDM',
  'Elysion – Never Forever': 'https://open.spotify.com/track/1gtiboFlPYIuaJSeF3fZk6',
  'Mohombi – Bumpy Ride': 'https://open.spotify.com/track/71R6zJsrF3ffc3TBFHfivX',
  'Bruce Springsteen – The River': 'https://open.spotify.com/track/7HrzErXq3TsKOY1gmdIShB',
  'Artemas – I Like The Way You Kiss Me': 'https://open.spotify.com/track/2GxrNKugF82CnoRFbQfzPf',
  'Robbie Williams – The Road To Mandalay': 'https://open.spotify.com/track/2HEQUu0ydMFIp6JDvCHFzZ',
  'Meat Loaf – Objects In The Rear View Mirror May Appear Closer…': 'https://open.spotify.com/track/2QLe0gNkUFKPlxJUauGLwh',
  'The Overslept – Little Miss Has-Been': 'https://open.spotify.com/track/0zPfjgmku5ey4LCKeRMTNV',
  'Panic! At the Disco – Miss Jackson': 'https://open.spotify.com/track/164AQ76bFQnan4jFOiMVV7',
  'Black – Wonderful Life': 'https://open.spotify.com/track/0IWtEFQBwRHaMXZQtGEVcM',
  'Chris de Burgh – In A Country Churchyard': 'https://open.spotify.com/track/0fJdDOyOxBFX84hMdveC96',
  'Supertramp – Fool’s Overture': 'https://open.spotify.com/track/5pSSEkT0963muzzIjsVkrs',
  'Madrugada – The Kids Are on High Street': 'https://open.spotify.com/track/0BE4xSpWoS6DDzqmQ1tSVC',
  'Alt-J – Matilda': 'https://open.spotify.com/track/77xZFu9TwwYnX7JNWfbavn',
  'Mumford & Sons – Sigh No More': 'https://open.spotify.com/track/0ZLtQDRQ8OeoaQvtK8MVHo',
  'Adele – Turning Tables': 'https://open.spotify.com/track/2eF2x1BkgilhaZ2AipRY8j',
  'The Mamas & The Papas – California Dreamin’': 'https://open.spotify.com/track/1ZEOIhSn6BKErV59bIgn76',
  'N.E.R.D. feat Lee Harvey & Vita – Lapdance': 'https://open.spotify.com/track/6FuAe03bP2SQT4TCDKhuGx',
  'The Kelly Family – Who’ll Come With Me': 'https://open.spotify.com/track/4WCOFB0MI88jHitX6a0poE',
  'The Wombats – Techno Fan': 'https://open.spotify.com/track/0VD69ricQ3Flm3apWr4FQS',
  'Damien Rice – 9 Crimes': 'https://open.spotify.com/track/5GZEeowhvSieFDiR8fQ2im',
  'Duncan Laurence – Arcade': 'https://open.spotify.com/track/1Xi84slp6FryDSCbzq4UCD',
  'Elton John – I’m Still Standing': 'https://open.spotify.com/track/1jDJFeK9x3OZboIAHsY9k2',
  'Within Temptation – Shot in the Dark': 'https://open.spotify.com/track/5JpbpsjhJeNwixBzbobklV',
  'Haevn – Bright Lights': 'https://open.spotify.com/track/5y2IxlUwQtWGnY4FAijQjm',
  'Beach House – Troublemaker': 'https://open.spotify.com/track/3Ib1w6wHwg0OSas2QhdJvl',
  'Mecano – Hijo De La Luna': 'https://open.spotify.com/track/7g3g2sqevicvurLTZ75JTA',
  'Metallica – Fade To Black': 'https://open.spotify.com/track/5nekfiTN45vlxG0eNJQQye',
  'Hero – Toen Ik Je Zag': 'https://open.spotify.com/track/6Ff8YmQ1Gc9d03q9JYe7sT',
  'Dido – Life For Rent': 'https://open.spotify.com/track/7nYS7mmZh0K8EbM8DBRwb9',
  'Lyriel – Dust to Dust': 'https://open.spotify.com/track/6AX15gFdndhRYNrsB0vwic',
  'Kayak – Ruthless Queen': 'https://open.spotify.com/track/14HPLWSrRNhSfxCswERQbw',
  'Rondé – We Gotta Have It All': 'https://open.spotify.com/track/6Hlhf1fSgY9g6TIPtEg8vn',
  'Razorlight – America': 'https://open.spotify.com/track/6bS7DqTuzrpkluB7boWmw2',
  'Tame Impala – Eventually': 'https://open.spotify.com/track/5M4yti0QxgqJieUYaEXcpw',
  'Muse – Madness': 'https://open.spotify.com/track/0c4IEciLCDdXEhhKxj4ThA',
  'Sue the Night – Wonderland': 'https://open.spotify.com/track/1KnEQhFi7COd2AJ5op8sif',
  'Eminem – Lose Yourself': 'https://open.spotify.com/track/5Z01UMMf7V1o0MzF86s6WJ',
  'McFly – The End': 'https://open.spotify.com/track/0GQjiIhGiJUwTvgF5unqqw',
  'Golden Earring – I Can’t Sleep Without You': 'https://open.spotify.com/track/4VUycAekQ39AXPiEQDGCbh',
  'Wildstylez feat. Niels Geusebroek – Year Of Summer': 'https://open.spotify.com/track/5U7NscpqQub6inkiFZApNG',
  'The Joy Formidable – Dance of the Lotus': 'https://open.spotify.com/track/2LivGkyfZfWASQ6dCSRXNe',
  'Cute Is What We Aim For – Navigate Me': 'https://open.spotify.com/track/7BWRB2MRG3vtAlVCxEgp3r',
  'Keane – This Is The Last Time': 'https://open.spotify.com/track/6IVlHRrjTKep5SS9kbcpTa',
  'Symphony X – When All Is Lost': 'https://open.spotify.com/track/68lu5r63e68LlUZ6snJEvI',
  'Half Moon Run – Call Me In The Afternoon': 'https://open.spotify.com/track/5dfKKLhIoNY7EbCgyGYnb9',
  'Wham – Last Christmas': 'https://open.spotify.com/track/2FRnf9qhLbvw8fu4IBXx78',
  'Billie Eilish – Getting Older': 'https://open.spotify.com/track/4HOryCnbme0zBnF8LWij3f',
  'Gigi d’Agostino – Star': 'https://open.spotify.com/track/5vth89NNdbTTj4U7l67mFn',
  'Eric Prydz – Call on Me': 'https://open.spotify.com/track/1As4KC3YYpu89aBt7EqL2m',
  'Metallica – Nothing Else Matters': 'https://open.spotify.com/track/6QAsrXPnMSXIbV0yEJHlEX',
  'Twenty One Pilots – Migraine': 'https://open.spotify.com/track/1X4DF3q5k1LPpTP4ZnpL96',
  'Maria Mena – Just Hold Me': 'https://open.spotify.com/track/7IPMUKKlLQEBuKVhNzwTR1',
  'Coldplay – Midnight': 'https://open.spotify.com/track/4GKk1uNzpxIptBuaY97Dkj',
  'Fall Out Boy – My Songs Know What You Did In The Dark': 'https://open.spotify.com/track/1rKRVRXykfmOga4BM9h53E',
  'Sue the Night – Mind Dear': 'https://open.spotify.com/track/26zgAcjieTBzhgA4HKTcqT',
  'The Carpenters – Sing': 'https://open.spotify.com/track/386bIxJPFIr5pVuVQTZIOm',
  'Bob Dylan – Hurricane': 'https://open.spotify.com/track/1lqMLr9Wj7SM2F9AikGcxN',
  'Mumford & Sons – White Blank Page': 'https://open.spotify.com/track/6BnY5XawSsp3dpjQ3FtqjT',
  'Halsey – Bad At Love': 'https://open.spotify.com/track/3OzCF9i6Ey7EkkAYJztmKp',
  'Coldplay – Adventure of a Lifetime': 'https://open.spotify.com/track/69uxyAqqPIsUyTO8txoP2M',
  'Dire Straits – Your Latest Trick': 'https://open.spotify.com/track/2oKOGvdJ5BQEiguaSQJJpc',
  'Destroy Boys – I Threw Glass at My Friend’s Eyes and Now I’m on Probation': 'https://open.spotify.com/track/5ot500QigZaa1tH5tQoR1C',
  'No Doubt – It’s My Life': 'https://open.spotify.com/track/1OutzYv6YiN93lrT3pJsWR',
  'Culture Beat – Mr. Vain': 'https://open.spotify.com/track/2JjDgorBAd8Er6IS5Weyok',
  'Dua Lipa – Be The One': 'https://open.spotify.com/track/1ixphys4A3NEXp6MDScfih',
  'Pixies – Where Is My Mind?': 'https://open.spotify.com/track/0KzAbK6nItSqNh8q70tb0K',
  'Dermot Kennedy – Better Days': 'https://open.spotify.com/track/48USW4aYqrylYWJmFPbC8A',
  'Akcent – Kylie': 'https://open.spotify.com/track/5lWs85eYNdGjAc9p3vcgD2',
  'Within Temptation – The Reckoning': 'https://open.spotify.com/track/6XnPopwCZ6odHVVqMsllL5',
  'Within Temptation – What Have You Done': 'https://open.spotify.com/track/2OHeJR6Cfvm42512gonFRh',
  'Joep Beving – Aeon': 'https://open.spotify.com/track/4qmfxVnkdt3bBGlbFsnUwA',
  'Of Monsters and Men – Thousand Eyes': 'https://open.spotify.com/track/6QzGqC6uS8RuMDDNxdJgPK',
  'Lange feat. Skye – Drifting Away': 'https://open.spotify.com/track/5n02YT0zcJ10Eq8IYusaNm',
  'DJ Fresh – Hot Right Now': 'https://open.spotify.com/track/3FsdYAv9VAUsDGDVgzTurN',
  'Nothing But Thieves – Amsterdam': 'https://open.spotify.com/track/454I78HEySdcHE8fcVabTb',
  'Coldplay – The Scientist': 'https://open.spotify.com/track/75JFxkI2RXiU7L9VXzMkle',
  'Keane – Somewhere Only We Know': 'https://open.spotify.com/track/1SKPmfSYaPsETbRHaiA18G',
  'Riva feat. Dannii Minogue – Who Do You Love Now?': 'https://open.spotify.com/track/35PEVVj0HGwvjIYuBZWvVr',
  'The Black Keys – Lonely Boy': 'https://open.spotify.com/track/5G1sTBGbZT5o4PNRc75RKI',
  'You Me At Six – Rescue Me': 'https://open.spotify.com/track/7DUCNQRudZwc5TzxThlaRg',
  'Muse – Knights of Cydonia': 'https://open.spotify.com/track/7ouMYWpwJ422jRcDASZB7P',
  'Dream Theater – The Count of Tuscany': 'https://open.spotify.com/track/2GV41X8idjOWKpKwUKIDJ6',
  'Chicane & Moya Brennan – Saltwater': 'https://open.spotify.com/track/7a1jKlij4hReZVlHNOuhai',
  'M83 – Midnight City': 'https://open.spotify.com/track/6GyFP1nfCDB8lbD2bG0Hq9',
  'Yellowcard – Lights and Sounds': 'https://open.spotify.com/track/4XOZaPYeMn9hcbpyS90NnD',
  'Half Moon Run – Everyone’s Moving Out East': 'https://open.spotify.com/track/2mg17l3EfdZ6bFX82rCwcU',
  'The Weeknd – Blinding Lights': 'https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b',
  'HAEVN – Trade It For The Night': 'https://open.spotify.com/track/5FdxCyHx8CSiP9TOS7oM0i',
  'Within Temptation – Forgiven': 'https://open.spotify.com/track/1uy9eKbA9e0Dg7bsjqGOZr',
  'Meat Loaf – It’s All Coming Back To Me Now': 'https://open.spotify.com/track/3bc2u7r6xTKh49klARzHiC',
  'Nightwish, Floor Jansen & Henk Poort – The Phantom of the Opera': 'https://open.spotify.com/track/1cmmoTr5B1zmhLSd5vIcIi',
  'Rondé – Work of Art': 'https://open.spotify.com/track/0Ec1NH8C0pa4x7ELcFsPpM',
  'Nightwish – Wishmaster': 'https://open.spotify.com/track/4mwiaj9c4V0pW5y8t9mYHa',
  'Tova – Nice Girl': 'doesnt exist',
  'Within Temptation – Destroyed': 'https://open.spotify.com/track/32G5tPEm1QgUsu05sQMcjq',
  'Beach House – Other People': 'https://open.spotify.com/track/0ftgoTIc4IMEUi9w4lJ3IS',
  'Skillet – Awake and Alive': 'https://open.spotify.com/track/0nkzd3yNniB767zSDDdLZ3',
  'Dotan – Home': 'https://open.spotify.com/track/0BVUA3FXqQLvZb7r4T22NJ',
  'Of Monsters and Men – King and Lionheart': 'https://open.spotify.com/track/310d8Vawp5kYDYrGrrTAzl',
  'Nightwish – The Islander': 'https://open.spotify.com/track/7Ce61NyQM0XfGbVHSUBBOG',
  'M83 – Go!': 'https://open.spotify.com/track/18mNRyfNGQvVfwTJo27sNR',
  'Major Lazer & DJ Snake – Lean On': 'https://open.spotify.com/track/2YWjW3wwQIBLNhxWKBQd16',
  'Delain – Moth to a Flame': 'https://open.spotify.com/track/4Oct1rxJ3hQtkgXxT3ktCA',
  'Volbeat – Lola Montez': 'https://open.spotify.com/track/34rCwPVIy1OZKfIbXC9KmN',
  'The Wombats – Let’s Dance To Joy Division': 'https://open.spotify.com/track/7v9Ne4758aGFfFc5avh89h',
  'The Moody Blues – Nights in White Satin': 'https://open.spotify.com/track/5w1ingzqrsJka9nlnEFB64',
  'The Cranberries – Ode To My Family': 'https://open.spotify.com/track/5kcsc92tGAjS0uvhDY3Mok',
  'Barclay James Harvest – Hymn': 'https://open.spotify.com/track/4eEDECI99JmE2w7H2VLUag',
  'Sonata Arctica – The Last Amazing Grays': 'https://open.spotify.com/track/4XsyxJ0DP6dStJTBgnmD8d',
  'The Jellyrox – Fade to Fiction': 'https://open.spotify.com/track/4GN17FTcK0UrO2kgbww2ak',
  'Delain – One Second': 'https://open.spotify.com/track/6gsgFHFxZTUL6W9j1sGeUD',
  'Makthaverskan – Asleep': 'https://open.spotify.com/track/5kt1mzWc81bDSWRppWAJIE',
  'Chvrches – Bury It': 'https://open.spotify.com/track/2J41GT1FtmMpsaJ5zcoJ5X',
  'Groove Coverage – Nothing Lasts Forever': 'https://open.spotify.com/track/6Nvx5zFrRcYsfEo8cT6GNM',
  'Rondé – Love Myself': 'https://open.spotify.com/track/0iBWf9gz65kHxuQkZkrNUc',
  'Light Blue Lawrence – Good Where I Am': 'https://open.spotify.com/track/7rnoU8F6ga9AaB5cqVEXCf',
  'We Came As Romans – I Knew You Were Trouble': 'https://open.spotify.com/track/2Owosq1UmHdHrL6h428lAn',
  'Of Verona – Castles': 'https://open.spotify.com/track/5Fh7b1GroaIwW6NIJdJxaG',
  'Fleetwood Mac – Everywhere': 'https://open.spotify.com/track/1prZ0pr6XoRCxcrC3MCL0M',
  'Twarres – Wer Bisto': 'https://open.spotify.com/track/6FoayFn7vcZvScTZ67HuZK',
  'Ava Max – Kings & Queens': 'https://open.spotify.com/track/7a53HqqArd4b9NF4XAmlbI',
  'Amorphis – Bad Blood': 'https://open.spotify.com/track/4AgV5p9YCgIhd9BbrAWXvY',
  'Sonata Arctica – Replica': 'https://open.spotify.com/track/2A4rfHIusMPUyTN2RAgsKw',
  'Steve Harley & Cockney Rebel – Tumbling Down': 'https://open.spotify.com/track/3MdE18B3pkKpfxrKfftJuG',
  'After Forever – Energize Me': 'https://open.spotify.com/track/3caX2bCmH0GmGnNfFPjd5k',
  'Golden Earring – Twilight Zone': 'https://open.spotify.com/track/1miXjv3X34Q9w7wDZoBnDz',
  'Coldplay – Clocks': 'https://open.spotify.com/track/0BCPKOYdS2jbQ8iyB56Zns',
  'Alan Walker – Ignite': 'https://open.spotify.com/track/1jLsirPDkUS2g4gnkYua58',
  'Linkin Park – One More Light': 'https://open.spotify.com/track/3xXBsjrbG1xQIm1xv1cKOt',
  'Bowling for Soup – Friends Chicks Guitars': 'https://open.spotify.com/track/4UV4Aj1Ktv3ZSfrAdE1flD',
  'Hurts – Wonderful Life': 'https://open.spotify.com/track/2pxpJ9lmbqPEIk3M7ezLR0',
  'White Lies – Take It Out On Me': 'https://open.spotify.com/track/2CAnSpdCbUu2ItxdbkdOfg',
  'Owl City – Honey and the Bee': 'https://open.spotify.com/track/34VWeivu3VF3PnkV6MRhNK',
  'Ed Sheeran – The A Team': 'https://open.spotify.com/track/1VdZ0vKfR5jneCmWIUAMxK',
  'Eiffel 65 – Blue': 'https://open.spotify.com/track/7lMIJ4EFWRVoAIPDpeGyM3',
  'R.E.M. – The One I Love': 'https://open.spotify.com/track/7707eDBpR4qtNFoQ6nQyeR',
  'Hurts – Silver Lining': 'https://open.spotify.com/track/3ww7sj1QovjTsGAjnHpiPU',
  'Go_A – Shum': 'https://open.spotify.com/track/29bhnde7Gvnp7rvY9zsq5S',
  'Hurts – Somebody To Die For': 'https://open.spotify.com/track/0GDz2tPdh6FbxJxM75SQB4',
  'Lights – Moonshine': 'https://open.spotify.com/track/4UcDxG7sJdVeX0jeR2QzKG',
  'George Michael – Careless Whisper': 'https://open.spotify.com/track/5WDLRQ3VCdVrKw0njWe5E5',
  'Biffy Clyro – Black Chandelier': 'https://open.spotify.com/track/2LWFw1lxYO3uX3T1kGhJpp',
  'Billy Joel – Piano Man': 'https://open.spotify.com/track/70C4NyhjD5OZUMzvWZ3njJ',
  'Moderat – Les Grandes Marches': 'https://open.spotify.com/track/3khLRTfeeRTGB2xVuuOKu4',
  'Manox – Autumn Shine': 'https://open.spotify.com/track/30D2iB84Wvu9UhXOgCbfAM',
  'Simon & Garfunkel – The Sound of Silence': 'https://open.spotify.com/track/3CepTOU9Y7FezTt0CF3lCw',
  'Fort Minor – Remember The Name': 'https://open.spotify.com/track/4nJUuE7GO6v9i6KTu67wFO',
  'Muse – Showbiz': 'https://open.spotify.com/track/2sCFFlnYg6Lk75GCcfSXEz',
  'Within Temptation – Hand of Sorrow': 'https://open.spotify.com/track/41j3TmJuJuSlHsqoX6L3dr',
  'Nothing But Thieves – Welcome To The DCC': 'https://open.spotify.com/track/1eivMnftGIAIeTDUfTssVX',
  'M83 – Solitude': 'https://open.spotify.com/track/49xgzcmtmEnsEDWSOMYWoD',
  'Keane – Bend & Break': 'https://open.spotify.com/track/4mPiTSD96K4Dha1irhqpW3',
  'Within Temptation – Memories': 'https://open.spotify.com/track/5qOA9jbfWAtxOJ8zY1ReYf',
  'Robin S – Show Me Love': 'https://open.spotify.com/track/4t0UsYzmmmZRMTWn77jiGF',
  'Moby – Go': 'https://open.spotify.com/track/0e8C9dPERvvARURkNOFrrC',
  'Röyksopp – Alpha Male': 'https://open.spotify.com/track/5ZRaHg5hwLATg2jWO0daXO',
  'The Boxer Rebellion – Diamonds': 'https://open.spotify.com/track/0GLv1X9sA8gqzZs98g1B11',
  'Jeckyll & Hyde – Frozen Flame': 'https://open.spotify.com/track/09mBO33FrA8DshDOmevWj3',
  'Auri – Night 13': 'https://open.spotify.com/track/2GxISQd2cNYGqZKm5b8tJJ',
  'Son Mieux – Multicolor': 'https://open.spotify.com/track/2ExdbieQffMXpY7ygN2YN9',
  'Bethel Music – Holy Forever': 'https://open.spotify.com/track/7FufqShqWlNP606lT9iNr1',
  'Survivor – Eye of the Tiger': 'https://open.spotify.com/track/2KH16WveTQWT6KOG9Rg6e2',
  'Editors – An End Has A Start': 'https://open.spotify.com/track/5jth1c4wa4BythOzap3qOU',
  'Mumford & Sons – Hopeless Wanderer': 'https://open.spotify.com/track/5A6LzyrBmTI9iCKetFj7v1',
  'Enrique Iglesias – Subeme La Radio': 'https://open.spotify.com/track/7nKBxz47S9SD79N086fuhn',
  'Story of the Year – Tear Me To Pieces': 'https://open.spotify.com/track/4o8iQ9HKmZP0D7eRcTnW0g',
  'Supertramp – Take The Long Way Home': 'https://open.spotify.com/track/46TLlKsmMNRQc53ukyFCtM',
  'Bløf – Aan de Kust': 'https://open.spotify.com/track/7yVyTfEMnR4p1LcAbo2uiF',
  'After Forever – Yield To Temptation': 'https://open.spotify.com/track/2HDfFgUUv6PXo5Iyx34SHb',
  'Placebo – Every You Every Me': 'https://open.spotify.com/track/2Srd8Jgif3kc6ou6Z4pSYJ',
  'Journey – Separate Ways': 'https://open.spotify.com/track/4NiyMmBdlVHpZWScgdBvnt',
  'Eleventyseven – Book of Secrets': 'https://open.spotify.com/track/2QHXIDrwApBkYFRWZjw4tO',
  'Blood Red Shoes – Don’t Ask': 'https://open.spotify.com/track/4vrJk0wLtNFiAeTo0lDOYP',
  'Skrillex – First Of The Year': 'https://open.spotify.com/track/5i7fZq3chLyCHo3VeB6goD',
  'The Fever 333 – Made An America': 'https://open.spotify.com/track/0Q6AD7e7d9tpN1dXL4qh5P',
  'Crystal Fighters – Plage': 'https://open.spotify.com/track/6y4sVRatVOlBRref1xUqTO',
  'Kate Bush – The Man With The Child In His Eyes': 'https://open.spotify.com/track/6uO2xVFeHvWpJIgnE2ulwy',
  'The Weeknd feat. Daft Punk – I Feel It Coming': 'https://open.spotify.com/track/5GXAXm5YOmYT0kL5jHvYBt',
  'Bring Me The Horizon – Go To Hell, For Heaven’s Sake': 'https://open.spotify.com/track/0Koh9yED8UuaXvg9p5lQdB',
  'Blossoms – Charlemagne': 'https://open.spotify.com/track/7H5WVBQdSnJ1zmu8JoD6pg',
  'Eros Ramazzotti – Se Bastasse Una Canzone': 'https://open.spotify.com/track/7dp45uA0Ws4TadWaMwdIRw',
  '3 Doors Down – Here Without You': 'https://open.spotify.com/track/3NLrRZoMF0Lx6zTlYqeIo4',
  'Golden Earring – Another 45 Miles': 'https://open.spotify.com/track/4CwgZ5RmLvJzBf1f48mGML',
  'Epica – Sense Without Sanity / The Impervious Code': 'https://open.spotify.com/track/1rwAncJ6I5Aw5BiBYdi1NX',
  'ByeAlex – Kedvesem': 'https://open.spotify.com/track/23fCWypxkzbzywnpM9opZm',
  'Linkin Park – Numb': 'https://open.spotify.com/track/2nLtzopw4rPReszdYBJU6h',
  'Nickelback – How You Remind Me': 'https://open.spotify.com/track/0gmbgwZ8iqyMPmXefof8Yf',
  'Swedish House Mafia – Don’t You Worry Child': 'https://open.spotify.com/track/2V65y3PX4DkRhy1djlxd9p',
  'The Joy Formidable – Forest Serenade': 'https://open.spotify.com/track/0vTqF4HHCUDAQ77RsZiHmn',
  'Foo Fighters – Stranger Things Have Happened': 'https://open.spotify.com/track/7zaZlzl0XhthNwH3GQcyZ0',
  'Enter Shikari – Pack of Thieves': 'https://open.spotify.com/track/5t9f9TeL5EIeYuD8pKv6FE',
  'David Guetta – Memories': 'https://open.spotify.com/track/7fLzbEOBOae9lUnOwr7Tse',
  'Yeah Yeah Yeahs – Heads Will Roll': 'https://open.spotify.com/track/4FRqM1mahmNdLOT9OQOr8q',
  'Backstreet Boys – I Want It That Way': 'https://open.spotify.com/track/2KMwtsWwL5QDtSpm814tju',
  'Crystal Lake feat. Beth – Dear God': 'https://open.spotify.com/track/5cwFuFFmqbit5imd3POXtY',
  'Of Monsters and Men – Empire': 'https://open.spotify.com/track/4M9lfUgDeLHu1fL2ZxZSlu',
  'Pink Floyd – Comfortably Numb': 'https://open.spotify.com/track/5HNCy40Ni5BZJFw1TKzRsC',
  'Muse – Supremacy': 'https://open.spotify.com/track/40pPI2TbaYSZlKfV44HRjn',
  'The Goo Goo Dolls – Iris': 'https://open.spotify.com/track/6Qyc6fS4DsZjB2mRW9DsQs',
  'Sera – Head Held High': 'https://open.spotify.com/track/14K6bAsr3aunhuVVy9cPqz',
  'Elbow – Lippy Kids': 'https://open.spotify.com/track/0hY82Rdf8woq4p5m0ZvfJZ',
  'Nirvana – Come As You Are': 'https://open.spotify.com/track/2RsAajgo0g7bMCHxwH3Sk0',
  'The Gaslight Anthem – ‘45': 'https://open.spotify.com/track/5LQN7c99Q8gvmh6xJcTZgj',
  'Within Temptation – Gatekeeper': 'https://open.spotify.com/track/2hcwHO0YiiuLlEmOAJh5B4',
  'Rob de Nijs – Zo Zal Het Zijn': 'https://open.spotify.com/track/6xSz2CF7P2RFUtv15vyvXp',
  'Krezip – All My Life': 'https://open.spotify.com/track/5A5RoEPhOr4TzKA2dRxNl0',
  'DJ THT & Scarlet – Live 2 Dance': 'https://open.spotify.com/track/5ozKaJdtDjpsRV5B9Pc2lu',
  'Nightwish – My Walden': 'https://open.spotify.com/track/3LgWFCHW1eZLZyfylrn88p',
  'Editors – Bones': 'https://open.spotify.com/track/2MAHdjGUA2Zm3thQnhWpTI',
  'Rufus Wainwright – Going To A Town': 'https://open.spotify.com/track/4XTGDKcerI21v4k1Au2H1L',
  'Editors – Smokers Outside The Hospital Doors': 'https://open.spotify.com/track/2ibNhXeLiX8fm7KQtQUIgl',
  'Kylie Minogue – Can’t Get You Out Of My Head': 'https://open.spotify.com/track/3E7ZwUMJFqpsDOJzEkBrQ7',
  'Oasis – Don’t Look Back In Anger': 'https://open.spotify.com/track/7ppPZa3TRUSGKaks9wH7VT',
  'XTM feat. Annia – Fly On The Wings Of Love': 'https://open.spotify.com/track/1vUUF0735UnBcL3fsUxFoB',
  'Alexander Brandon – Hell Freezes Over': 'https://open.spotify.com/track/1iITForrnY8MhSjEu6SuLG',
  'Maustetytöt – Talvi Talvikin kanssa': 'https://open.spotify.com/track/0tHYz1E2odedOoeBkMeqt6',
  'Within Temptation – Our Farewell': 'https://open.spotify.com/track/7064U7N7XT8CeNRurTpADK',
  'Foo Fighters – Learn to Fly': 'https://open.spotify.com/track/5OQsiBsky2k2kDKy2bX2eT',
  'Owl City – Fireflies': 'https://open.spotify.com/track/3DamFFqW32WihKkTVlwTYQ',
  'Owl City – Dreams Don’t Turn To Dust': 'https://open.spotify.com/track/6FnVOw8plIlNFFU2Uhz2po',
  'Marija Serifovic – Molitva': 'https://open.spotify.com/track/1ue71r2sNUvl4LSqvgVVcZ',
  'Elton John – Can You Feel The Love Tonight': 'https://open.spotify.com/track/32RxZnEk5KyWUTZR4azxbD',
  'Megara & DJ Lee – Musical Society': 'https://open.spotify.com/track/3uZZPt9H1ggXvy4pXj6rZy',
  'Biffy Clyro – God & Satan': 'https://open.spotify.com/track/6nDHogPDqb1SMphYCQQs7w',
  'Panic At The Disco – Nicotine': 'https://open.spotify.com/track/5Q4H1XkVHxQjnrHCUpS61d',
  'The Motors – Airport': 'https://open.spotify.com/track/2z7xtlgcHFjAPFCYgQLxUN',
  'Klein Orkest – Later is al lang begonnen': 'https://open.spotify.com/track/5Ue7OtuBeeDYdd24NBnuXI',
  'Like Torches – Keep Your Head High': 'https://open.spotify.com/track/1Rau8YnmdopkBQ9TH6wcXN',
  'Abel – Onderweg': 'https://open.spotify.com/track/1nduf8eirAAiVLXoC1C7cz',
  'Meat Loaf – Life Is A Lemon And I Want My Money Back': 'https://open.spotify.com/track/5mv2a02p47YqxLtRUFCQk9',
  'Nirvana – Lithium': 'https://open.spotify.com/track/5vHLwhxxlGzmClMcxRRFPr',
  'Rondé – Undecided': 'https://open.spotify.com/track/67HfJMTt2jley2uzWzocKe',
  'Editors – In This Light And On This Evening': 'https://open.spotify.com/track/2vojVtg4lvIEBYHDkeS4mo',
  'Nightwish – Crownless': 'https://open.spotify.com/track/5pf8gamghe8jg36VEkcUWO',
  'Radical Face – Welcome Home': 'https://open.spotify.com/track/2s6EnALYuQbEgB1C4mfUCO',
  'Alan Walker – The Spectre': 'https://open.spotify.com/track/2DGa7iaidT5s0qnINlwMjJ',
  'Jackson Browne – The Load Out & Stay': 'https://open.spotify.com/track/0Bk7XD1UQoqI0M8cTgmkNf',
  'Kensington – Riddles': 'https://open.spotify.com/track/1QcwwjyRqLuuP2jt1hrjsG',
  'Di-Rect – Through the Looking Glass': 'https://open.spotify.com/track/7j2TJXhcE1aAzB6Evmgvm0',
  'Crystal Lake – High': 'https://open.spotify.com/track/4MEquiLH2xNlvWfqO1wT1g',
  'Twenty One Pilots – Guns For Hands': 'https://open.spotify.com/track/04rkWgfd6v9xXMAHBVP9Sr',
  'Muse – Supermassive Black Hole': 'https://open.spotify.com/track/3lPr8ghNDBLc2uZovNyLs9',
  'The War on Drugs – I Don’t Live Here Anymore': 'https://open.spotify.com/track/5Uou8idst1XJc0F6MRAk5S',
  'Odette – Love Kills': 'doesnt exist',
  'David Kane – Stargate To Heaven': 'doesnt exist',
  'Harry Styles – Sign of the Times': 'https://open.spotify.com/track/5Ohxk2dO5COHF1krpoPigN',
  'Bastille – Bad Blood': 'https://open.spotify.com/track/4VYpW7AZnPftcuJqCwW70L',
  'Nirvana – The Man Who Sold The World': 'https://open.spotify.com/track/15VRO9CQwMpbqUYA7e6Hwg',
  'Yellowcard – Awakening': 'https://open.spotify.com/track/0Orpf6gjHFDkrntyjLR4SF',
  'Yellowcard – Always Summer': 'https://open.spotify.com/track/4ilpew1AcHAc38SIf4GQbN',
  'E-Type – Far Up In The Air': 'https://open.spotify.com/track/5Sb2n3xoH74PiOy3zLmyyZ',
  'Bowling for Soup – High School Never Ends': 'https://open.spotify.com/track/1bhjMY5O0ZjB41OHcdRH0a',
  'Clouseau – Domino': 'https://open.spotify.com/track/4WhVZjzVTThcPmPK6m8kfD',
  'Metallica – Enter Sandman': 'https://open.spotify.com/track/3DwQ7AH3xGD9h65ezslm6q',
  'Alice Deejay – Better Off Alone': 'https://open.spotify.com/track/5XVjNRubJUW0iPhhSWpLCj',
  'Ralph McTell – Streets of London': 'https://open.spotify.com/track/2zwH1NlxBEpzVlvzXNHQso',
  'Son Mieux – Have A Little Faith': 'https://open.spotify.com/track/6i4roOAXcuHWfmFuYFXZti',
  'Toy Box – The Sailor Song': 'https://open.spotify.com/track/13i5XpzqdQ5KTIKatuIVoa',
  'Kelly Clarkson – Behind These Hazel Eyes': 'https://open.spotify.com/track/0AKAxdNkwq9ZxRdW1DN9zW',
  'DJane HouseKat – All The Time': 'https://open.spotify.com/track/78easkZAIVZuMHzagJSs7K',
  'The Vaccines – All My Friends Are Falling In Love': 'https://open.spotify.com/track/0JAQUGJudVlhRoAqqhVoYX',
  'Lacuna Coil – Spellbound': 'https://open.spotify.com/track/4DXswc4p8mel7E6C1ZSHDq',
  'Nightwish – Sacrament of Wilderness': 'https://open.spotify.com/track/6MNfIYJglkFfhDt8Lmye8d',
  'Tones And I – Dance Monkey': 'https://open.spotify.com/track/2XU0oxnq2qxCpomAAuJY8K',
  'Hammerfall – Hearts On Fire': 'https://open.spotify.com/track/0eV3PB3T0OxW4feG1DlOjQ',
  'Within Temptation – Dangerous': 'https://open.spotify.com/track/3BYtn1zK991rGwWo5TW9e6',
  'The Police – Message in a Bottle': 'https://open.spotify.com/track/1oYYd2gnWZYrt89EBXdFiO',
  'Queensrÿche – Silent Lucidity': 'https://open.spotify.com/track/0E8Vm5HMDYRyEYFEKudvcX',
  'Twenty One Pilots – Jumpsuit': 'https://open.spotify.com/track/1E1uGhNdBe6Dddbgs2KqtZ',
  'Delain – To Live Is To Die': 'https://open.spotify.com/track/0boDHMJHmuRmeagg3MqMCE',
  'David Guetta feat. Akon – Sexy Bitch': 'https://open.spotify.com/track/2dGxjfhFXDIUX9h5ImyKkE',
  'Faithless – Insomnia': 'https://open.spotify.com/track/3dX6WDwnHwYzB5t754oB4T',
  'Netsky – Come Alive': 'https://open.spotify.com/track/7JSRgtiKwuyhZBbJ52cFkb',
  'Katarsis – Tavo Akys': 'https://open.spotify.com/track/1imPa2lzxmLKggLCpkBAoo',
  'Within Temptation – Never-Ending Story': 'https://open.spotify.com/track/7DRCln6I1jENSWRILU3u3I',
  'Lights – Slow Down': 'https://open.spotify.com/track/3Aik6gPLnyqY6mWP0PnVXk',
  'Billie Eilish – Your Power': 'https://open.spotify.com/track/042Sl6Mn83JHyLEqdK7uI0',
  'E-Type – Princess of Egypt': 'https://open.spotify.com/track/1kaL8kRZYdzYFDcMP7RvxD',
  'Eleventyseven – Back When We Were Kids': 'https://open.spotify.com/track/1dQUG92ex4jOyohaUvUlo7',
  'Of Monsters And Men – Mountain Sound': 'https://open.spotify.com/track/3SPVZJzf1Hs30rB6yXVf2y',
  'Marco Borsato – Het Donker': 'https://open.spotify.com/track/18TTc3qGgZf7ITrnmEDIoG',
  'Anouk – Places To Go': 'https://open.spotify.com/track/2kIMDGHkZPCwK0MD2IlXzR',
  'Coldplay – In My Place': 'https://open.spotify.com/track/2nvC4i2aMo4CzRjRflysah',
  'The Killers – Mr. Brightside': 'https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B',
  'Yellowcard – Rough Landing, Holly': 'https://open.spotify.com/track/40S4RjkGS3DhYgTMy0aZvX',
  'First Aid Kit – My Silver Lining': 'https://open.spotify.com/track/6tCLQ3LO1V9l6qdrrwdV6q',
  'Kaiser Chiefs – Ruby': 'https://open.spotify.com/track/2sgBTNHz9ckmqj3rx3ez4M',
  'Nightwish – Walking In The Air': 'https://open.spotify.com/track/7MGRbcEL599rSUIhgh0JZF',
  'Biffy Clyro – Sounds Like Balloons': 'https://open.spotify.com/track/11Ipy4FtS5DQKvZ7B4FBzm',
  'Gigi d’Agostino – The Riddle': 'https://open.spotify.com/track/0ZqveF2rEFlz2oqF2xrriP',
  'Within Temptation – Sinéad': 'https://open.spotify.com/track/6sI8ojHlABbk9nvEtPYK5v',
  'Of Monsters and Men – From Finner': 'https://open.spotify.com/track/16oGsGvhNhTihlZAYLp2wm',
  'Coldplay – Fly On [O]': 'https://open.spotify.com/track/77yuzxCS3csrgTPSW0pvyk',
  'Taylor Swift – Anti-Hero': 'https://open.spotify.com/track/0V3wPSX9ygBnCm8psDIegu',
  'Girl in Red – I Need To Be Alone': 'https://open.spotify.com/track/2wHmH8OGgU6qi8NrLl0VRY',
  'Yellowcard – Waiting Game': 'https://open.spotify.com/track/2sEtycfSeULwGx5RjbaoAB',
  'Pet Shop Boys – It’s A Sin': 'https://open.spotify.com/track/3GNwCZIv4xKUiyoaQfj9Ah',
  'Coldplay – Hurts Like Heaven': 'https://open.spotify.com/track/6WF4hzdGXvXd1joERSXJjm',
  'Placebo – Ashtray Heart': 'https://open.spotify.com/track/3FqGGjtL4tbZYa7IFd6kYN',
  'Mr. President – Coco Jamboo': 'https://open.spotify.com/track/5fRvePkRGdpn2nKacG7I6d',
  'Paramore – Still Into You': 'https://open.spotify.com/track/1yjY7rpaAQvKwpdUliHx0d',
  'Andras Kallay-Saunders – Running': 'https://open.spotify.com/track/3gdZA8Jct5VBFUmugE6hic',
  'KAJ – Bara Bada Bastu': 'https://open.spotify.com/track/2gThkoApt6B7ajBWZRLAVv',
  'Sven-R-G & Bass-T pres. Uto – On a Party Trip': 'https://open.spotify.com/track/3jZXcPZvqzi3IXgPfEGwiZ',
  'Talco – St. Pauli': 'https://open.spotify.com/track/3O4vUrfm0KVVT8TW5xTsKR',
  'Foo Fighters – Come Alive': 'https://open.spotify.com/track/4P4s2KHOw0uISbLI3zkHtD',
  'Dizzee Rascal & Armand van Helden – Bonkers': 'https://open.spotify.com/track/6ddQ5KCkvCggk3j6KdA0zL',
  'The Smiths – Heaven Knows I’m Miserable Now': 'https://open.spotify.com/track/1H5N26VqHR4JhuaRKY2I0u',
  'Lights – Saviour': 'https://open.spotify.com/track/5dSTEwEBqCutDNXtueASXg',
  'Sonata Arctica – I Have A Right': 'https://open.spotify.com/track/4CmtxfLMOwBvrrE7OFBzCq',
  'Queen – Bohemian Rhapsody': 'https://open.spotify.com/track/2OBofMJx94NryV2SK8p8Zf',
  'Editors – Forgiveness': 'https://open.spotify.com/track/6zmiC9RTPMxjsKPuFxt5KJ',
  'Eminem – Without Me': 'https://open.spotify.com/track/2YaiY5Cr8IFv0X0YRZDNzV',
  'Yellowcard – Transmission Home': 'https://open.spotify.com/track/1zNnXOBp0lXMx9vk2tjfGx',
  'Sia – Cheap Thrills': 'https://open.spotify.com/track/27SdWb2rFzO6GWiYDBTD9j',
  'Tarja – I Walk Alone': 'https://open.spotify.com/track/4CgT8F1diUtGQBRBITEIjz',
  'The Beatles – Yesterday': 'https://open.spotify.com/track/3BQHpFgAp4l80e1XslIjNI',
  'Blind Channel – We Are No Saints': 'https://open.spotify.com/track/3BPdKJxzfJX63N7LYLDpI6',
  'Boudewijn de Groot – Testament': 'https://open.spotify.com/track/0iqLx1WpZdKT3E2oqLLO3f',
  'Fall Out Boy – Alone Together': 'https://open.spotify.com/track/07cY8RVMoK11sRdLIUINW6',
  'D-Code feat. Emma – Out Of My Hands': 'https://open.spotify.com/track/3eDAE6FfngRlietwhWYooL',
  'Enter Shikari – Sorry You’re Not A Winner': 'https://open.spotify.com/track/6PwxotrB99xgatKVzibmkz',
  'Arcade Fire – Here Comes The Night Time': 'https://open.spotify.com/track/4OZyVAbGOcrv4BYv5xDjet',
  'The Gaslight Anthem – Handwritten': 'https://open.spotify.com/track/7dqaE8YtE14X1QXMgVNMW4',
  'Lights – Heavy Rope': 'https://open.spotify.com/track/4z42iWJCMndPGlQWaR2crf',
  'Kaiser Chiefs – I Predict A Riot': 'https://open.spotify.com/track/75D3n6wnFQmu1HVmLAlWM4',
  'Pink Floyd – Another Brick In The Wall': 'https://open.spotify.com/track/4gMgiXfqyzZLMhsksGmbQV',
  'Armin van Buuren & Sharon Den Adel – In And Out Of Love': 'https://open.spotify.com/track/57nKL06bKwjaM5Y0aMtY9v',
  'DeWolff – Diamonds': 'https://open.spotify.com/track/2ega8tIpIe6sGx8m3T1yrX',
  'Red Hot Chilli Peppers – Californication': 'https://open.spotify.com/track/48UPSzbZjgc449aqz8bxox',
  'Angerfist – Take U Back': 'https://open.spotify.com/track/0fAGhiSB9k1OuAJNJgO1po',
  'My Chemical Romance – Na Na Na': 'https://open.spotify.com/track/5BB0Jzw60KyfSTyjJqtely',
  'Frans Halsema – De Vroeg Grijze Generatie': 'https://open.spotify.com/track/17xBhz7QIZowqtWssbVrsE',
  'Yellowcard – For You And Your Denial': 'https://open.spotify.com/track/79t5XYhIMyZPOVyKVSJxM2',
  'Toto – Pamela': 'https://open.spotify.com/track/3LFdvM7nIV8t02zyhYLvJo',
  'Alan Parsons Project – Eye in the Sky': 'https://open.spotify.com/track/2sIbHjfJ3nbMXNz4w03fWv',
  'Kinderen voor Kinderen 17 – Hij Wil Niet Meer Naar School': 'https://open.spotify.com/track/4nSVckkVGm6j3mTpawubLf',
  'Eleventyseven – Nostalgiatopia': 'https://open.spotify.com/track/4pWg4yUhPR75CEw5ZJ4F4n',
  'Dire Straits – Walk of Life': 'https://open.spotify.com/track/2DmZ7aPhT5jkqLIYxTpQlJ',
  'Goldband – Noodgeval': 'https://open.spotify.com/track/2LcmbuYX7tyR4DWy3b273L',
  'Enya – Only Time': 'https://open.spotify.com/track/6FLwmdmW77N1Pxb1aWsZmO',
  'Rondé – Hard To Say Goodbye': 'https://open.spotify.com/track/3AT0yKs2cWdKII3JBxzmqv',
  'Bob Dylan – Blowin’ in the Wind': 'https://open.spotify.com/track/18GiV1BaXzPVYpp9rmOg0E',
  'Within Temptation – In Perfect Harmony': 'https://open.spotify.com/track/6Hr2VaAEpFvwgDTnTDe1W3',
  'The Proclaimers – I’m Gonna Be': 'https://open.spotify.com/track/67iAlVNDDdddxqSD2EZhFs',
  'Yellowcard – Life of Leaving Home': 'https://open.spotify.com/track/2ZGDchsLjI5EIRBqMS15Gt',
  'Who See – Igranka': 'https://open.spotify.com/track/0Jp4dF9e1BmUzhlGKcdjg6',
  'Nelly Furtado – Turn Off The Light': 'https://open.spotify.com/track/4gM2BugovNf4bvXdjZODzG',
  'Blue Öyster Cult –': 'https://open.spotify.com/track/5QTxFnGygVM4jFQiBovmRo',
  'Muse – Follow Me': 'https://open.spotify.com/track/6r9tjMWLv8fNdZKKTnqCEr',
  'Niviro – Demons': 'https://open.spotify.com/track/6IvaH3A29h0j9Ejz2O1TeL',
  'Marillion – Kayleigh': 'https://open.spotify.com/track/1Dsd1Nu06UbNmelEhPxKgB',
  'Jenn Johnson – Come To Me': 'https://open.spotify.com/track/2gB9n0nkSJoLgkgo5XnBdC',
  'Muse – Algorithm': 'https://open.spotify.com/track/7f0vVL3xi4i78Rv5Ptn2s1',
  'Foo Fighters – Let It Die': 'https://open.spotify.com/track/2XvrMHbSO077Ajg7QTTNdY',
  'Kylie Minogue – Love At First Sight': 'https://open.spotify.com/track/6ua8mbyHXTHpAmGyGpFAS2',
  'Sarina Paris – Just About Enough': 'https://open.spotify.com/track/4CzAfowHigL9opOtIgumQQ',
  'Tracy Chapman – Fast Car': 'https://open.spotify.com/track/2M9ro2krNb7nr7HSprkEgo',
  'The White Stripes – Seven Nation Army': 'https://open.spotify.com/track/3dPQuX8Gs42Y7b454ybpMR',
  'Loreen – Euphoria': 'https://open.spotify.com/track/2knr7ikPt4l7bk92qS4ZXW',
  'Kraantje Pappie – Waar Is Kraan': 'https://open.spotify.com/track/6QIFpz9gWsdsFUYD9RfPHP',
  'Marco Borsato – Dromen Zijn Bedrog': 'https://open.spotify.com/track/2o4iWZOFE8kkl0tK66WADw',
  'Darude – Sandstorm': 'https://open.spotify.com/track/6Sy9BUbgFse0n0LPA5lwy5',
  'Within Temptation – Somewhere': 'https://open.spotify.com/track/0h46IYZnCzjROtiegnYC0Z',
  'Milow – You Don’t Know': 'https://open.spotify.com/track/6tuiVu3EhyiUGNCyWO0qET',
  'Flogging Molly – Drunken Lullabies': 'https://open.spotify.com/track/7caiyAewYYoWu5rZZgQWgn',
  'You Me At Six – No One Does It Better': 'https://open.spotify.com/track/5hOFLQvwOjk1Dp8mNIXEU5',
  'Peter Maffay – So Bist Du': 'https://open.spotify.com/track/3a5Pk82SnxIfGbuu78jCGp',
  'Faul & Wad Ad – Changes': 'https://open.spotify.com/track/2SdMEke7JCBEo8t60iyw2r',
  'Calvin Harris – Feels': 'https://open.spotify.com/track/6BaCraQ9xeLYg4Sb9TBT2X',
  'Birdy – Skinny Love': 'https://open.spotify.com/track/4RL77hMWUq35NYnPLXBpih',
  'Royal Blood – Lights Out': 'https://open.spotify.com/track/1060gzllf4b0UETAXisR5l',
  'Dub FX – Concord': 'https://open.spotify.com/track/6twhXsTJQa3QFwO1WkTRcR',
  'Hurts – Blind': 'https://open.spotify.com/track/6pTt7MJxHYnpovS4w5NbRI',
  'Groove Coverage – Angel From Above': 'https://open.spotify.com/track/0tnQZeHq3oWpjKB7FABDTl',
  'Panic! At the Disco – LA Devotee': 'https://open.spotify.com/track/2fmCA13dwQQOGBIbIOWRiJ',
  'Emilie Autumn – Opheliac': 'https://open.spotify.com/track/6HkGQ1F0ZtPHbnp1GCdLZK',
  'Nightwish – Storytime': 'https://open.spotify.com/track/5IhtaTempjlVlPmSgI0FQS',
  'Britney Spears – Hold It Against Me': 'https://open.spotify.com/track/7Dyq1bhhjknLKEGg4k5NLr',
  'Muse – We Are Fucking Fucked': 'https://open.spotify.com/track/5IumuUJqNO7K5SvniuDrBz',
  'The War on Drugs – Up All Night': 'https://open.spotify.com/track/3U9HrZM2sAZhqdSvZMj2oq',
  'Ava Max – Sweet But Psycho': 'https://open.spotify.com/track/7DnAm9FOTWE3cUvso43HhI',
  'Klaas & Ruiz – Feel Only Love': 'https://open.spotify.com/track/4716vLdETXfm5BcLg39Xg4',
  'Alexander Brandon – Jazz Be Damned': 'https://open.spotify.com/track/5pFAEckM15f2RlVneuUnkL',
  'A-ha – Forever Not Yours': 'https://open.spotify.com/track/6xSFUvaGsknS91piYekmXP',
  'Editors – Munich': 'https://open.spotify.com/track/1TF8mSG5YHyaS4o3NeBSAo',
  'Delerium – Innocente': 'https://open.spotify.com/track/1rppYjHqG7HOP4mZGGywnF',
  'Clannad – Theme from Harry’s Game': 'https://open.spotify.com/track/7CTSDg60OC15XUJusBLPuo',
  'Twenty One Pilots – Polarize': 'https://open.spotify.com/track/6GmkJJMe9U1tEcrJ3Hq3A1',
  'Joe Jackson – Real Men': 'https://open.spotify.com/track/5ImoRAws2ni1qYWrLR7sqi',
  'Alizee – Moi.. Lolita': 'https://open.spotify.com/track/6e0LjNPkRqxIAlmmdjWSV8',
  'IIO – Rapture': 'https://open.spotify.com/track/0OSAJEA0ekX6pr2nuiPzX7',
  'Roel C. Verburg – Ik Ben Een Zombie': 'https://open.spotify.com/track/36yY5lRysnpTrcb8wSylwq',
  'Kensington – Sorry': 'https://open.spotify.com/track/07uuo1yEND3oinbFZnYOvx',
  'Doctor P – Sweet Shop': 'https://open.spotify.com/track/4YWLXT4VwXzxnh26ibqzov',
  'Sia – Unstoppable': 'https://open.spotify.com/track/2J2Z1SkXYghSajLibnQHOa',
  'Master Blaster – Can Delight': 'https://open.spotify.com/track/0SvQZoEY2zBhbOv5O2kytE',
  'Within Temptation – Mother Earth': 'https://open.spotify.com/track/0vZzCD8Gy1w6ph5PzLctVo',
  'Eleventyseven – New Rock Bottom': 'https://open.spotify.com/track/6xcSaEsBbnK8RNhuRBr6PK',
  'Cradle of Filth – From the Cradle to Enslave': 'https://open.spotify.com/track/14JG4VbsqeLsFuDJlkybOT',
  'Het Goede Doel – Zwijgen': 'https://open.spotify.com/track/5g1cGCG5hJavBunc7DBmxN',
  'Within Temptation – The Cross': 'https://open.spotify.com/track/01rZM6iLGA6EkFD6J6yh0f',
  'Felix the Housecat – Silverscreen': 'https://open.spotify.com/track/4pLQGLLDP7gC5UQKyLeic6',
  'Nelly Furtado – …On The Radio': 'https://open.spotify.com/track/7G5Fepm6qOfG75W43Gwp1q',
  'Klein Orkest – Over de Muur': 'https://open.spotify.com/track/3lKu0TSctAQJqt9IAOUHcm',
  'Ced Tecknoboy feat. Yvar – More': 'https://open.spotify.com/track/2x158kZHWD7yO3JiDTkcKK',
  'Skyla – Breaking Free': 'doesnt exist',
  'Enter Shikari – Constellations': 'https://open.spotify.com/track/2gwwLFbdmLlsQ1GYe3GA7c',
  'Robert Long – Flink Zijn': 'doesnt exist',
  'Linkin Park – Crawling': 'https://open.spotify.com/track/4yQI9wjNF0gYUHwjNpCLQ9',
  'Frank Boeijen Groep – Zwart Wit': 'https://open.spotify.com/track/34OjTz1ttUEq2iLGxjJ5s9',
  'Belinda Carlisle – Heaven Is A Place On Earth': 'https://open.spotify.com/track/37Q5anxoGWYdRsyeXkkNoI',
  'Rag‘n’Bone Man – Human': 'https://open.spotify.com/track/58zsLZPvfflaiIbNWoA22O',
  'Britney Spears – Baby One More Time': 'https://open.spotify.com/track/3MjUtNVVq3C8Fn0MP3zhXa',
  'Dewi – Left of Center': 'https://open.spotify.com/track/7zu3uCpFss6UNNl5iyOQb0',
  'Hurts – Ready To Go': 'https://open.spotify.com/track/1DjLBipaNw74WmZkvTyho9',
  'Chuck Berry – Johnny B. Goode': 'https://open.spotify.com/track/2QfiRTz5Yc8DdShCxG1tB2',
  'Son Mieux – Tonight': 'https://open.spotify.com/track/3v2dHPoXhfVVZ6HQBfjQOh',
  'Linkin Park – Rebellion': 'https://open.spotify.com/track/3zZ009FB8sc8JghwVrbLFq',
  'Queen – Who Wants To Live Forever': 'https://open.spotify.com/track/77X4MKKCVpGSHsaErgCLzT',
  'A-ha – Take On Me': 'https://open.spotify.com/track/2WfaOiMkCvy7F5fcp2zZ8L',
  'Frank Boeijen Groep – Linda': 'https://open.spotify.com/track/37sOxkeHNES53xCk6mAK8h',
  'Owl City – Beautiful Times': 'https://open.spotify.com/track/5m4hXylTxAEtPkwgrBZim8',
  'Twenty One Pilots – Trees': 'https://open.spotify.com/track/2EDI0r2F9Qhvi7XiEoctHH',
  'Peter Skellern – You’re A Lady': 'https://open.spotify.com/track/6B0Tw3hiQyOkQLXuMC07fl',
  'Lights – Same Sea': 'https://open.spotify.com/track/6FRuWHPja7mwNx0kyxfQ61',
  'Twarres – She Couldn’t Laugh': 'https://open.spotify.com/track/6WWs0E3jqFiOqzRb93q2vY',
  'P.O.D. – Youth Of The Nation': 'https://open.spotify.com/track/0UrWr7Jnu1heq1o99ZwUd0',
  'Alcazar – Crying At The Discotheque': 'https://open.spotify.com/track/7gQAFGUyHPcY0cQNPsjMf0',
  'Split Enz – Message To My Girl': 'https://open.spotify.com/track/2YnKRdpWWapJWeouwfYqRa',
  'Kane – Rain Down On Me': 'https://open.spotify.com/track/2rRY9uu2SQge80Ifw58cfU',
  'TheFatRat feat. Laura Brehm – We’ll Meet Again': 'https://open.spotify.com/track/7nDkXyN86D6iszJdl0r8YB',
  'Fleetwood Mac – Go Your Own Way': 'https://open.spotify.com/track/07GvNcU1WdyZJq3XxP0kZa',
  'Foo Fighters – But Honestly': 'https://open.spotify.com/track/4SMbJ6BAY9LdudY8v7HJpH',
  'Papa Roach – Last Resort': 'https://open.spotify.com/track/5W8YXBz9MTIDyrpYaCg2Ky',
  'Half Moon Run – Hotel in Memphis': 'https://open.spotify.com/track/08bKFswxaiQge0cOiUSt60',
  'Duncan Laurence – Love Don’t Hate It': 'https://open.spotify.com/track/3WpCAAxdEOY5L4tT6Dt2H8',
  'Will and the People – Salamander': 'https://open.spotify.com/track/2NWffNCDkKJ4DxD14I66Mr',
  'Meat Loaf – Everything Louder Than Everything Else': 'https://open.spotify.com/track/13eUUBaOxzA1Xpw6LZZS96',
  'Maneskin – Zitti e Buoni': 'https://open.spotify.com/track/776AftMmFFAWUIEAb3lHhw',
  'The Weeknd – Save Your Tears': 'https://open.spotify.com/track/5QO79kh1waicV47BqGRL3g',
  'Blanks – Lost in the Moment': 'https://open.spotify.com/track/3nF5FjUP4W0QBxW4JCyUoa',
  'Passenger – Fear of Fear': 'https://open.spotify.com/track/17VHkJ5zeQBRHL3i0J0jT8',
  'The Dubliners – Wild Rover': 'https://open.spotify.com/track/6K9cjIloubdwJxwxrDcETI',
  'Yellowcard – Only One': 'https://open.spotify.com/track/0gZp88SA5OcujHLDGkxtI3',
  'Technikore – 4AM': 'https://open.spotify.com/track/4Owa7EbS6iS0xBGJAzLUNP',
  'Limp Bizkit – My Way': 'https://open.spotify.com/track/2gSVKxPDww9Eep5rdvtdem',
  'The Joy Formidable – The Greatest Light Is The Greatest Shade': 'https://open.spotify.com/track/6TsD6VmsM0Lqt4mI9XnKOJ',
  'The Cure – Play For Today': 'https://open.spotify.com/track/77HYwsktlwB37zyEH9dgYY',
  'Meat Loaf – Rock & Roll Dreams Come Through': 'https://open.spotify.com/track/4YaoFW42YXgVr5U1UzIANs',
  'Within Temptation – Iron': 'https://open.spotify.com/track/3iSgRJUrMKHLglnrQrQ6kO',
  'Crowded House – Don’t Dream It’s Over': 'https://open.spotify.com/track/56GbZVwxMdf1DENCluYS8A',
  'Muse – Plug in Baby': 'https://open.spotify.com/track/2UKARCqDrhkYDoVR4FN5Wi',
  'Soft Cell – Tainted Love': 'https://open.spotify.com/track/0cGG2EouYCEEC3xfa0tDFV',
  'Kaiser Chiefs – Every Day I Love You Less And Less': 'https://open.spotify.com/track/5dvBeCMTzUNjyWIcuykzyh',
  'Yellowcard – How I Go': 'https://open.spotify.com/track/5DRyV3ql5cpXGKjYtoUuaw',
  'Bob Sinclar – Love Generation': 'https://open.spotify.com/track/7iee007QypdrTXbLVF5KuF',
  'Beastie Boys – Sabotage': 'https://open.spotify.com/track/0Puj4YlTm6xNzDDADXHMI9',
  'The Radar Station – Face Full of Lines': 'https://open.spotify.com/track/5VbgnRAWB92Y9UV2t3SKc8',
  'M83 – For The Kids': 'https://open.spotify.com/track/28Zx43w8wP0ZTpS1y9yqFX',
  'Enter Shikari – Gandhi Mate Gandhi': 'https://open.spotify.com/track/0IOtWMCvUNJtFR77d0AYfm',
  'Green Day – Wake Me Up When September Ends': 'https://open.spotify.com/track/3ZffCQKLFLUvYM59XKLbVm',
  'Chvrches – Empty Threat': 'https://open.spotify.com/track/6vnSLVdwhPYqMoDxpftrmf',
  'Bakermat – Baiana': 'https://open.spotify.com/track/74p1Dr6LeP3UpD7N7btbK9',
  'Cyndi Lauper – Time after Time': 'https://open.spotify.com/track/7o9uu2GDtVDr9nsR7ZRN73',
  'DJ Klubbingman – Magic Summer Night': 'https://open.spotify.com/track/5zzKCgTWKW61ieeU6uFLVy',
  'Spandau Ballet – Gold': 'https://open.spotify.com/track/2X9fsxb6O6bYEopJYmUbNC',
  'R.E.M. – E-Bow The Letter': 'https://open.spotify.com/track/2S3wW83zk0CosLGYN7jfor',
  'Kygo & Plested – Me Before You': 'https://open.spotify.com/track/3zLIKAkrLLwzNe4RsD5EBC',
  'Meat Loaf – Paradise By The Dashboardlight': 'https://open.spotify.com/track/2g7gviEeJr6pyxO7G35EWQ',
  'Of Monsters and Men – Yellow Light': 'https://open.spotify.com/track/3hs6kchwaeSe967AMMYTrp',
  'Cradle of Filth – Her Ghost in the Fog': 'https://open.spotify.com/track/0IVdlBreRkZn0ftoUwB0T6',
  'Nightwish – Ghost River': 'https://open.spotify.com/track/3sTZ4DxyZ4PcKxKj4MHLI8',
  'Enter Shikari – The Last Garrison': 'https://open.spotify.com/track/5zZ79IgPs6vOWf7NRwC1d2',
  'Boudewijn de Groot – Avond': 'https://open.spotify.com/track/3n3F07lHLyRKwqg4q64eYA',
  'Bachman-Turner Overdrive – You Ain’t Seen Nothing Yet': 'https://open.spotify.com/track/0HOrDVS349XFcpCYsO2hAP',
  'Mother Love Bone – Man of Golden Words': 'https://open.spotify.com/track/7yEKGqv8FyIzuPVWZtPe8Z',
  'Jason Upton – In The Silence': 'https://open.spotify.com/track/136a6EmnAV5uO5nyoXWlUc',
  'Vampire Weekend – Harmony Hall': 'https://open.spotify.com/track/39exKIvycQDgs4T6uXdyu0',
  'Ed Sheeran – Shape Of You': 'https://open.spotify.com/track/7qiZfU4dY1lWllzX7mPBI3',
  'Lasgo – Tonight': 'https://open.spotify.com/track/6P1c1rhgwR7NbR0CSOa8FC',
  'DeWolff – The Pistol': 'https://open.spotify.com/track/5EGQrf2xwhnMr6Mi5Dcfws',
  'Boudewijn de Groot – Verdronken Vlinder': 'https://open.spotify.com/track/6WVSZMmvptfhEJLeq1xYDv',
  'The Rasmus – In The Shadows': 'https://open.spotify.com/track/1fr92Vupmcs2vgLMFVQ7rd',
  'David Guetta & Sia – Flames': 'https://open.spotify.com/track/2mBPqbzgjIELxd86CdxC7v',
  'Macklemore & Ryan Lewis – Thrift Shop': 'https://open.spotify.com/track/6CjtS2JZH9RkDz5UVInsa9',
  'Snelle – In De Schuur': 'https://open.spotify.com/track/4d2NiGtCaVrMihMfarLE8o',
  'Roel C. Verburg – Vriendin van Vroeger': 'https://open.spotify.com/track/57ev7ljxvPu1LNvweQCWuH',
  'Tiësto – Lethal Industry': 'https://open.spotify.com/track/3NfcNWiWysF7aV5b3Jd9CE',
  'Halsey – Sorry': 'https://open.spotify.com/track/3IgUCMkHS4RgHdngIlporF',
  'Herman van Veen – Hilversum 3': 'https://open.spotify.com/track/72kwuUDDy3gJrOLvKsV8LZ',
  'Semisonic – Closing Time': 'https://open.spotify.com/track/1A5V1sxyCLpKJezp75tUXn',
  'Het Goede Doel – Nooduitgang': 'https://open.spotify.com/track/2wsfSsNfqlkCaUGaWvGYcz',
  'Melee – Built To Last': 'https://open.spotify.com/track/4x907tqu1ai70Sz6xLrK2E',
  'Meat Loaf – Bad For Good': 'https://open.spotify.com/track/47ezHhM8d4Kdab6vxU75gv',
  'C-Bool – House Baby': 'https://open.spotify.com/track/7haS2Ue3w86N0Fu1zyxvJz',
  'Nothing But Thieves – Trip Switch': 'https://open.spotify.com/track/13QI6bq0U8HMK7gUpAwFBK',
  'My Chemical Romance – Teenagers': 'https://open.spotify.com/track/7j31rVgGX9Q2blT92VBEA0',
  'Andy Jay Powell – 4 Ever & 1 Night': 'https://open.spotify.com/track/66oni1VbzSfkvk8OLyeJm3',
  'Nightwish – Noise': 'https://open.spotify.com/track/0RZVAhyB8vhxQz6ITjiuyA',
  'Compact Disco – Sound Of Our Hearts': 'https://open.spotify.com/track/7HsxEALEUjB2pOH5Yhuy4S',
  'Cat Stevens – Morning Has Broken': 'https://open.spotify.com/track/7lJcPqSxbSyDE4bLnXeoqr',
  'Linkin Park – Heavy': 'https://open.spotify.com/track/104buTcnP2AsxqB7U1FIZ4',
  'Nightwish – Harvest': 'https://open.spotify.com/track/06h4HxzQkqx45lCRxDe4lA',
  'Yellowcard – Way Away': 'https://open.spotify.com/track/63IIUzd6eJBfCGIcF8MFnJ',
  'The Vaccines – Wreckin’ Bar': 'https://open.spotify.com/track/1K5vb3Yu4F8yMaHggtdpDY',
  'Nits – In the Dutch Mountains': 'https://open.spotify.com/track/7JLjdk1PX5LMBxM5zfYCQV',
  'Käärijä – Cha Cha Cha': 'https://open.spotify.com/track/5RX8T3EoTuXcybAxe6oPAw',
  'Kavinsky – Zenith': 'https://open.spotify.com/track/4DrUFg8VvQKwzdUL0cGiVe',
  'Blood Red Shoes – When We Wake': 'https://open.spotify.com/track/5Xa7ik4hTSFFcJTnc5KKpC',
}
