name: Test application
on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Test
        run: |
          npm ci
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
