name: Test application
on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Run Unit Tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Run End-to-End Tests
        run: npm run e2e:run
